import 'package:cc_domain/features/pr_review/domain/services/lockfile_diff.dart';
import 'package:test/test.dart';

/// Exercises [LockfileDiffer] — the offline dependency-change extractor behind
/// the PR Review Hub's "Dependencies" panel.
void main() {
  const differ = LockfileDiffer();

  // --- fixtures -------------------------------------------------------------

  const pubBase = '''
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  archive:
    dependency: transitive
    description:
      name: archive
      sha256: "aaaa"
      url: "https://pub.dev"
    source: hosted
    version: "3.4.10"
  args:
    dependency: transitive
    description:
      name: args
      sha256: "bbbb"
      url: "https://pub.dev"
    source: hosted
    version: "2.4.2"
  meta:
    dependency: transitive
    description:
      name: meta
      sha256: "cccc"
      url: "https://pub.dev"
    source: hosted
    version: 1.11.0
sdks:
  dart: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"
''';

  const pubHead = '''
# Generated by pub
packages:
  archive:
    dependency: transitive
    description:
      name: archive
      sha256: "dddd"
      url: "https://pub.dev"
    source: hosted
    version: "4.0.0"
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: "eeee"
      url: "https://pub.dev"
    source: hosted
    version: "1.18.0"
  meta:
    dependency: transitive
    description:
      name: meta
      sha256: "cccc"
      url: "https://pub.dev"
    source: hosted
    version: 1.11.0
sdks:
  dart: ">=3.4.0 <4.0.0"
''';

  const npmBase = '''
{
  "name": "app",
  "version": "1.0.0",
  "lockfileVersion": 3,
  "requires": true,
  "packages": {
    "": {
      "name": "app",
      "version": "1.0.0",
      "dependencies": { "semver": "^7.5.4" }
    },
    "apps/web": {
      "name": "@app/web",
      "version": "0.0.1"
    },
    "node_modules/@types/node": {
      "version": "20.11.5",
      "resolved": "https://registry.npmjs.org/@types/node/-/node-20.11.5.tgz",
      "integrity": "sha512-aaaa=="
    },
    "node_modules/left-pad": {
      "version": "1.3.0"
    },
    "node_modules/lru-cache": {
      "version": "10.0.1"
    },
    "node_modules/semver": {
      "version": "7.5.4",
      "dependencies": { "lru-cache": "^6.0.0" }
    },
    "node_modules/semver/node_modules/lru-cache": {
      "version": "6.0.0"
    }
  }
}
''';

  const npmHead = '''
{
  "name": "app",
  "version": "1.0.0",
  "lockfileVersion": 3,
  "packages": {
    "": { "name": "app", "version": "1.0.0" },
    "node_modules/@types/node": {
      "version": "22.0.0"
    },
    "node_modules/lru-cache": {
      "version": "10.0.1"
    },
    "node_modules/ms": {
      "version": "2.1.3"
    },
    "node_modules/semver": {
      "version": "7.6.0"
    }
  }
}
''';

  const npmV1 = '''
{
  "name": "app",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "@types/node": {
      "version": "18.19.3",
      "resolved": "https://registry.npmjs.org/@types/node/-/node-18.19.3.tgz",
      "integrity": "sha512-bbbb=="
    },
    "lodash": {
      "version": "4.17.20",
      "resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.20.tgz"
    }
  }
}
''';

  const pnpmBase = '''
lockfileVersion: '9.0'

settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false

importers:

  .:
    dependencies:
      react:
        specifier: ^17.0.2
        version: 17.0.2

packages:

  '@babel/code-frame@7.23.5':
    resolution: {integrity: sha512-aaaa==}
    engines: {node: '>=6.9.0'}

  left-pad@1.3.0:
    resolution: {integrity: sha512-bbbb==}

  react@17.0.2:
    resolution: {integrity: sha512-cccc==}

snapshots:

  react@17.0.2:
    dependencies:
      loose-envify: 1.4.0
''';

  const pnpmHead = '''
lockfileVersion: '9.0'

packages:

  '@babel/code-frame@7.23.5':
    resolution: {integrity: sha512-aaaa==}

  react@18.2.0:
    resolution: {integrity: sha512-dddd==}

  react-dom@18.2.0(react@18.2.0):
    resolution: {integrity: sha512-eeee==}
    peerDependencies:
      react: ^18.2.0
''';

  const pnpmLegacy = '''
lockfileVersion: 5.4

specifiers:
  react: ^17.0.2

packages:

  /@babel/code-frame/7.18.6:
    resolution: {integrity: sha512-ffff==}
    engines: {node: '>=6.9.0'}
    dev: true

  /left-pad/1.3.0:
    resolution: {integrity: sha512-gggg==}

  /react/17.0.2:
    resolution: {integrity: sha512-hhhh==}
    engines: {node: '>=0.10.0'}
''';

  const yarnBase = '''
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.16.7":
  version "7.18.6"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.18.6.tgz#aaaa"
  integrity sha512-aaaa==
  dependencies:
    "@babel/highlight" "^7.18.6"

left-pad@^1.3.0:
  version "1.3.0"
  resolved "https://registry.yarnpkg.com/left-pad/-/left-pad-1.3.0.tgz#bbbb"
  integrity sha512-bbbb==

lodash@^4.17.20, lodash@^4.17.21:
  version "4.17.20"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.20.tgz#cccc"
  integrity sha512-cccc==
''';

  const yarnHead = '''
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.16.7":
  version "7.23.5"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.23.5.tgz#dddd"
  integrity sha512-dddd==

lodash@^4.17.20, lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#eeee"
  integrity sha512-eeee==

ms@^2.1.3:
  version "2.1.3"
  resolved "https://registry.yarnpkg.com/ms/-/ms-2.1.3.tgz#ffff"
  integrity sha512-ffff==
''';

  // --- detection ------------------------------------------------------------

  group('LockfileEcosystem.detect', () {
    test('recognizes each lockfile by basename', () {
      expect(LockfileEcosystem.detect('pubspec.lock'), LockfileEcosystem.pub);
      expect(
        LockfileEcosystem.detect('apps/web/package-lock.json'),
        LockfileEcosystem.npm,
      );
      expect(
        LockfileEcosystem.detect('frontend/pnpm-lock.yaml'),
        LockfileEcosystem.pnpm,
      );
      expect(
        LockfileEcosystem.detect('packages/ui/yarn.lock'),
        LockfileEcosystem.yarn,
      );
    });

    test('normalizes Windows separators', () {
      expect(
        LockfileEcosystem.detect(r'apps\web\yarn.lock'),
        LockfileEcosystem.yarn,
      );
    });

    test('returns null for anything that is not a lockfile', () {
      expect(LockfileEcosystem.detect('lib/main.dart'), isNull);
      expect(LockfileEcosystem.detect('pubspec.yaml'), isNull);
      expect(LockfileEcosystem.detect('package.json'), isNull);
      expect(LockfileEcosystem.detect(''), isNull);
      // A directory that merely ends with the name is still not the file.
      expect(LockfileEcosystem.detect('yarn.lock/inner.txt'), isNull);
    });
  });

  group('LockfileEcosystem.fromName', () {
    test('round-trips every wire name', () {
      for (final value in LockfileEcosystem.values) {
        expect(LockfileEcosystem.fromName(value.wireName), value);
      }
    });

    test('returns null rather than guessing an ecosystem', () {
      expect(LockfileEcosystem.fromName('cargo'), isNull);
      expect(LockfileEcosystem.fromName(''), isNull);
      expect(LockfileEcosystem.fromName(null), isNull);
    });
  });

  // --- pubspec.lock ---------------------------------------------------------

  group('pubspec.lock', () {
    test('reads quoted and bare versions under packages only', () {
      final versions = differ.parseVersions(LockfileEcosystem.pub, pubBase);
      expect(versions, {
        'archive': '3.4.10',
        'args': '2.4.2',
        'meta': '1.11.0',
      });
      // `sdks:` is a sibling top-level key, not a dependency.
      expect(versions.containsKey('dart'), isFalse);
      expect(versions.containsKey('flutter'), isFalse);
    });

    test('diffs add, remove and upgrade', () {
      final diff = differ.diff(
        filePath: 'pubspec.lock',
        baseContent: pubBase,
        headContent: pubHead,
      );
      expect(diff, isNotNull);
      expect(diff!.ecosystem, LockfileEcosystem.pub);
      expect(diff.added, {'collection': '1.18.0'});
      expect(diff.removed, {'args': '2.4.2'});
      expect(diff.upgraded, [
        const DependencyUpgrade(name: 'archive', from: '3.4.10', to: '4.0.0'),
      ]);
      expect(diff.upgraded.single.majorBump, isTrue);
      expect(diff.churn, 3);
      expect(diff.isEmpty, isFalse);
      expect(diff.bestEffort, isFalse);
    });

    test('an identical lockfile is an empty diff', () {
      final diff = differ.diff(
        filePath: 'pubspec.lock',
        baseContent: pubBase,
        headContent: pubBase,
      );
      expect(diff!.isEmpty, isTrue);
      expect(diff.churn, 0);
    });

    test('a truncated block yields no version rather than a partial one', () {
      const truncated = '''
packages:
  archive:
    dependency: transitive
    description:
''';
      expect(differ.parseVersions(LockfileEcosystem.pub, truncated), isEmpty);
    });

    test('garbage yields an empty map without throwing', () {
      expect(
        differ.parseVersions(LockfileEcosystem.pub, 'not a lockfile at all'),
        isEmpty,
      );
      expect(differ.parseVersions(LockfileEcosystem.pub, '   \n\n'), isEmpty);
    });
  });

  // --- package-lock.json ----------------------------------------------------

  group('package-lock.json', () {
    test('reads the v2/v3 packages map, scopes included', () {
      final versions = differ.parseVersions(LockfileEcosystem.npm, npmBase);
      expect(versions['@types/node'], '20.11.5');
      expect(versions['left-pad'], '1.3.0');
      expect(versions['semver'], '7.5.4');
      // The `""` root and the `apps/web` workspace are the project itself.
      expect(versions.containsKey(''), isFalse);
      expect(versions.containsKey('@app/web'), isFalse);
      expect(versions.containsKey('app'), isFalse);
    });

    test('a nested copy is named by its last node_modules segment', () {
      const nestedOnly = '''
{
  "lockfileVersion": 3,
  "packages": {
    "": { "name": "app" },
    "node_modules/semver/node_modules/lru-cache": { "version": "6.0.0" }
  }
}
''';
      final versions = differ.parseVersions(LockfileEcosystem.npm, nestedOnly);
      expect(versions, {'lru-cache': '6.0.0'});
    });

    test('the shallowest copy of a duplicated package wins', () {
      // `npmBase` holds lru-cache twice: hoisted at 10.0.1 and nested at 6.0.0.
      final versions = differ.parseVersions(LockfileEcosystem.npm, npmBase);
      expect(versions['lru-cache'], '10.0.1');
    });

    test('falls back to the v1 dependencies map', () {
      final versions = differ.parseVersions(LockfileEcosystem.npm, npmV1);
      expect(versions, {'@types/node': '18.19.3', 'lodash': '4.17.20'});
    });

    test('diffs add, remove and upgrade', () {
      final diff = differ.diff(
        filePath: 'apps/web/package-lock.json',
        baseContent: npmBase,
        headContent: npmHead,
      );
      expect(diff, isNotNull);
      expect(diff!.ecosystem, LockfileEcosystem.npm);
      expect(diff.added, {'ms': '2.1.3'});
      expect(diff.removed, {'left-pad': '1.3.0'});
      expect(diff.upgraded, [
        const DependencyUpgrade(
          name: '@types/node',
          from: '20.11.5',
          to: '22.0.0',
        ),
        const DependencyUpgrade(name: 'semver', from: '7.5.4', to: '7.6.0'),
      ]);
      expect(diff.upgraded.first.majorBump, isTrue);
      expect(diff.upgraded.last.majorBump, isFalse);
      expect(diff.churn, 4);
      expect(diff.bestEffort, isFalse);
    });

    test('malformed JSON yields an empty map without throwing', () {
      expect(
        differ.parseVersions(LockfileEcosystem.npm, '{"packages": {'),
        isEmpty,
      );
      expect(
        differ.parseVersions(LockfileEcosystem.npm, 'this is not json'),
        isEmpty,
      );
      // Valid JSON of the wrong shape is just as unusable.
      expect(differ.parseVersions(LockfileEcosystem.npm, '[1, 2, 3]'), isEmpty);
      expect(differ.parseVersions(LockfileEcosystem.npm, '{}'), isEmpty);
    });
  });

  // --- pnpm-lock.yaml -------------------------------------------------------

  group('pnpm-lock.yaml', () {
    test('reads the modern `name@version` keys, scopes included', () {
      final versions = differ.parseVersions(LockfileEcosystem.pnpm, pnpmBase);
      expect(versions, {
        '@babel/code-frame': '7.23.5',
        'left-pad': '1.3.0',
        'react': '17.0.2',
      });
      // Structural keys must not be mined as packages.
      expect(versions.containsKey('resolution'), isFalse);
      expect(versions.containsKey('dependencies'), isFalse);
      expect(versions.containsKey('.'), isFalse);
    });

    test('reads the legacy `/name/version` keys, scopes included', () {
      final versions = differ.parseVersions(LockfileEcosystem.pnpm, pnpmLegacy);
      expect(versions, {
        '@babel/code-frame': '7.18.6',
        'left-pad': '1.3.0',
        'react': '17.0.2',
      });
    });

    test('strips the resolved peer suffix from a snapshot key', () {
      final versions = differ.parseVersions(LockfileEcosystem.pnpm, pnpmHead);
      expect(versions['react-dom'], '18.2.0');
    });

    test('diffs add, remove and upgrade and flags bestEffort', () {
      final diff = differ.diff(
        filePath: 'pnpm-lock.yaml',
        baseContent: pnpmBase,
        headContent: pnpmHead,
      );
      expect(diff, isNotNull);
      expect(diff!.ecosystem, LockfileEcosystem.pnpm);
      expect(diff.added, {'react-dom': '18.2.0'});
      expect(diff.removed, {'left-pad': '1.3.0'});
      expect(diff.upgraded, [
        const DependencyUpgrade(name: 'react', from: '17.0.2', to: '18.2.0'),
      ]);
      expect(diff.upgraded.single.majorBump, isTrue);
      expect(diff.churn, 3);
      expect(diff.bestEffort, isTrue);
    });

    test('garbage yields an empty map without throwing', () {
      expect(
        differ.parseVersions(LockfileEcosystem.pnpm, 'packages:\n  broken'),
        isEmpty,
      );
      expect(
        differ.parseVersions(LockfileEcosystem.pnpm, '@@@ ///: :::'),
        isEmpty,
      );
    });
  });

  // --- yarn.lock ------------------------------------------------------------

  group('yarn.lock', () {
    test('reads scoped and multi-spec headers', () {
      final versions = differ.parseVersions(LockfileEcosystem.yarn, yarnBase);
      expect(versions, {
        '@babel/code-frame': '7.18.6',
        'left-pad': '1.3.0',
        'lodash': '4.17.20',
      });
    });

    test('every spec on one header maps to the same package', () {
      const multi = '''
lodash@^4.17.20, lodash@~4.17.21, "lodash@4.x":
  version "4.17.21"
''';
      final versions = differ.parseVersions(LockfileEcosystem.yarn, multi);
      expect(versions, {'lodash': '4.17.21'});
    });

    test('accepts the `version: "x"` spelling too', () {
      const colonForm = '''
ms@^2.1.3:
  version: "2.1.3"

debug@^4.3.4:
  version: 4.3.4
''';
      final versions = differ.parseVersions(LockfileEcosystem.yarn, colonForm);
      expect(versions, {'ms': '2.1.3', 'debug': '4.3.4'});
    });

    test('skips the Yarn Berry `__metadata` block', () {
      const berry = '''
__metadata:
  version: 6
  cacheKey: 8

"lodash@npm:^4.17.21":
  version "4.17.21"
''';
      final versions = differ.parseVersions(LockfileEcosystem.yarn, berry);
      expect(versions.containsKey('__metadata'), isFalse);
      expect(versions['lodash'], '4.17.21');
    });

    test('diffs add, remove and upgrade and flags bestEffort', () {
      final diff = differ.diff(
        filePath: 'packages/ui/yarn.lock',
        baseContent: yarnBase,
        headContent: yarnHead,
      );
      expect(diff, isNotNull);
      expect(diff!.ecosystem, LockfileEcosystem.yarn);
      expect(diff.added, {'ms': '2.1.3'});
      expect(diff.removed, {'left-pad': '1.3.0'});
      expect(diff.upgraded, [
        const DependencyUpgrade(
          name: '@babel/code-frame',
          from: '7.18.6',
          to: '7.23.5',
        ),
        const DependencyUpgrade(name: 'lodash', from: '4.17.20', to: '4.17.21'),
      ]);
      expect(diff.upgraded.every((u) => u.majorBump), isFalse);
      expect(diff.churn, 4);
      expect(diff.bestEffort, isTrue);
    });

    test('garbage yields an empty map without throwing', () {
      expect(
        differ.parseVersions(LockfileEcosystem.yarn, '### broken\n  version'),
        isEmpty,
      );
      expect(differ.parseVersions(LockfileEcosystem.yarn, ',,,,,,'), isEmpty);
    });
  });

  // --- ordering & unknown paths --------------------------------------------

  group('LockfileDiffer.diff', () {
    test('returns null for a path that is not a lockfile', () {
      expect(
        differ.diff(
          filePath: 'lib/main.dart',
          baseContent: pubBase,
          headContent: pubHead,
        ),
        isNull,
      );
    });

    test('orders every collection by name', () {
      const base = '''
packages:
  zeta:
    version: "1.0.0"
  alpha:
    version: "1.0.0"
  mid:
    version: "1.0.0"
''';
      const head = '''
packages:
  zeta:
    version: "2.0.0"
  alpha:
    version: "2.0.0"
  mid:
    version: "2.0.0"
''';
      final diff = differ.diff(
        filePath: 'pubspec.lock',
        baseContent: base,
        headContent: head,
      );
      expect(diff!.upgraded.map((u) => u.name).toList(), [
        'alpha',
        'mid',
        'zeta',
      ]);
    });

    test('an empty base reads as a wholly added dependency set', () {
      final diff = differ.diff(
        filePath: 'pubspec.lock',
        baseContent: '',
        headContent: pubHead,
      );
      expect(diff!.added.keys.toList(), ['archive', 'collection', 'meta']);
      expect(diff.removed, isEmpty);
      expect(diff.upgraded, isEmpty);
      expect(diff.churn, 3);
    });
  });

  // --- majorBump ------------------------------------------------------------

  group('DependencyUpgrade.majorBump', () {
    DependencyUpgrade upgrade(String from, String to) =>
        DependencyUpgrade(name: 'x', from: from, to: to);

    test('is true when the leading component increases', () {
      expect(upgrade('1.2.3', '2.0.0').majorBump, isTrue);
      expect(upgrade('0.9.0', '1.0.0').majorBump, isTrue);
      expect(upgrade('9.0.0', '10.0.0').majorBump, isTrue);
      expect(upgrade('v1.0.0', 'v2.0.0').majorBump, isTrue);
    });

    test('is false for a same-major move', () {
      expect(upgrade('1.2.3', '1.3.0').majorBump, isFalse);
      expect(upgrade('4.17.20', '4.17.21').majorBump, isFalse);
      expect(upgrade('1.0.0', '1.0.0').majorBump, isFalse);
      expect(upgrade('1.0.0-beta.1', '1.0.0').majorBump, isFalse);
    });

    test('is false for a downgrade', () {
      expect(upgrade('2.0.0', '1.9.0').majorBump, isFalse);
    });

    test('flags an unparseable pair that changed', () {
      expect(upgrade('git+abc1234', 'git+def5678').majorBump, isTrue);
      expect(upgrade('1.0.0', 'file:../local').majorBump, isTrue);
      expect(upgrade('main', 'main').majorBump, isFalse);
    });
  });

  // --- serialization --------------------------------------------------------

  group('serialization', () {
    test('DependencyDiff round-trips through JSON', () {
      const original = DependencyDiff(
        ecosystem: LockfileEcosystem.pnpm,
        added: {'react-dom': '18.2.0'},
        removed: {'left-pad': '1.3.0'},
        upgraded: [
          DependencyUpgrade(name: 'react', from: '17.0.2', to: '18.2.0'),
        ],
        bestEffort: true,
      );
      final restored = DependencyDiff.fromJson(original.toJson());
      expect(restored, original);
      expect(restored!.churn, 3);
      expect(restored.bestEffort, isTrue);
    });

    test('an empty diff round-trips', () {
      const original = DependencyDiff(ecosystem: LockfileEcosystem.pub);
      final restored = DependencyDiff.fromJson(original.toJson());
      expect(restored, original);
      expect(restored!.isEmpty, isTrue);
      expect(restored.bestEffort, isFalse);
    });

    test('a computed diff survives the round-trip', () {
      final diff = differ.diff(
        filePath: 'yarn.lock',
        baseContent: yarnBase,
        headContent: yarnHead,
      )!;
      expect(DependencyDiff.fromJson(diff.toJson()), diff);
    });

    test('DependencyDiff.fromJson returns null on a malformed blob', () {
      expect(DependencyDiff.fromJson(const {}), isNull);
      expect(DependencyDiff.fromJson(const {'ecosystem': 'cargo'}), isNull);
      expect(DependencyDiff.fromJson(const {'ecosystem': 42}), isNull);
    });

    test('DependencyDiff.fromJson drops unusable members', () {
      final restored = DependencyDiff.fromJson(const {
        'ecosystem': 'npm',
        'added': {'ok': '1.0.0', 'bad': 7},
        'removed': 'not a map',
        'upgraded': [
          {'name': 'react', 'from': '17.0.2', 'to': '18.2.0'},
          {'name': 'broken'},
          'not a map',
        ],
      });
      expect(restored, isNotNull);
      expect(restored!.added, {'ok': '1.0.0'});
      expect(restored.removed, isEmpty);
      expect(restored.upgraded, [
        const DependencyUpgrade(name: 'react', from: '17.0.2', to: '18.2.0'),
      ]);
      expect(restored.bestEffort, isFalse);
    });

    test('DependencyDiff.fromJson tolerates wrongly-typed members', () {
      final restored = DependencyDiff.fromJson(const {
        'ecosystem': 'yarn',
        'upgraded': 'not a list',
        'bestEffort': 1,
      });
      expect(restored, isNotNull);
      expect(restored!.upgraded, isEmpty);
      expect(restored.bestEffort, isFalse);
      expect(restored.isEmpty, isTrue);
    });

    test('DependencyUpgrade round-trips and rejects a bad shape', () {
      const upgrade = DependencyUpgrade(
        name: '@types/node',
        from: '20.11.5',
        to: '22.0.0',
      );
      expect(DependencyUpgrade.fromJson(upgrade.toJson()), upgrade);
      expect(DependencyUpgrade.fromJson(const {'name': 'x'}), isNull);
      expect(
        DependencyUpgrade.fromJson(const {'name': 'x', 'from': 1, 'to': '2'}),
        isNull,
      );
    });

    test('equality and hashCode ignore map ordering', () {
      const a = DependencyDiff(
        ecosystem: LockfileEcosystem.npm,
        added: {'a': '1.0.0', 'b': '2.0.0'},
      );
      const b = DependencyDiff(
        ecosystem: LockfileEcosystem.npm,
        added: {'b': '2.0.0', 'a': '1.0.0'},
      );
      expect(a, b);
      expect(a.hashCode, b.hashCode);
      expect(
        a == const DependencyDiff(ecosystem: LockfileEcosystem.npm),
        isFalse,
      );
    });
  });
}
