// GENERATED BY tool/gen_icon_seams.py — DO NOT EDIT.
// The icon constants below are self-documenting (name == glyph); per-field doc
// comments would be pure noise.
// ignore_for_file: public_member_api_docs
import 'package:flutter/widgets.dart';

/// Icons used by cc_remote, referenced directly against the Phosphor Regular
/// font vendored by cc_ui (`packages/cc_ui/fonts/Phosphor-Regular.ttf`).
///
/// We deliberately depend on no icon package. Such a package exposes each
/// style as a class of ~1530 `static const IconData` fields; on Flutter web
/// the dev compiler (DDC) lazily links a library the first time one of its
/// members is accessed and linking that giant library overflows the JS stack
/// — crashing with a `StackOverflowError` before the first screen can render.
/// cc_remote is a web PWA, so this is fatal.
///
/// Generated by `tool/gen_icon_seams.py` — edit the mapping there, never
/// this file.
@staticIconProvider
abstract final class AppIcons {
  static const String _family = 'PhosphorRegular';
  static const String _package = 'cc_ui';

  static const IconData arrowDown = IconData(
    0xe03e,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData arrowLeft = IconData(
    0xe058,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData arrowRight = IconData(
    0xe06c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData bookmark = IconData(
    0xe0ea,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData bookmarkCheck = IconData(
    0xe0ea,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData bot = IconData(
    0xe762,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData calendar = IconData(
    0xe108,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData calendarDays = IconData(
    0xe108,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData check = IconData(
    0xe182,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData chevronDown = IconData(
    0xe136,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData chevronRight = IconData(
    0xe13a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData chevronsDown = IconData(
    0xe126,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData circleCheck = IconData(
    0xe184,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData circleDot = IconData(
    0xe3ee,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData circleSlash = IconData(
    0xe32c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData circleX = IconData(
    0xe4f8,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData clock = IconData(
    0xe19a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData cloudOff = IconData(
    0xe1b6,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData externalLink = IconData(
    0xe5de,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData eye = IconData(
    0xe220,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData file = IconData(
    0xe230,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData fileText = IconData(
    0xe23a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gitBranch = IconData(
    0xe278,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gitCommit = IconData(
    0xe27a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gitMerge = IconData(
    0xe280,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gitPullRequest = IconData(
    0xe282,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gitPullRequestDraft = IconData(
    0xe602,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData globe = IconData(
    0xe288,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData hash = IconData(
    0xe2a2,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData image = IconData(
    0xe2ca,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData imageOff = IconData(
    0xe7a8,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData inbox = IconData(
    0xe4aa,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData languages = IconData(
    0xe4a2,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData layers = IconData(
    0xe466,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData listFilter = IconData(
    0xe266,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData loader = IconData(
    0xeb44,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData logOut = IconData(
    0xe42a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData mapPin = IconData(
    0xe316,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData messageCircle = IconData(
    0xe168,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData messageSquare = IconData(
    0xe15c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData minus = IconData(
    0xe32a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData monitor = IconData(
    0xe32e,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData moon = IconData(
    0xe330,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData newspaper = IconData(
    0xe344,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData palette = IconData(
    0xe6c8,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData plus = IconData(
    0xe3d4,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData refreshCw = IconData(
    0xe036,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData scanLine = IconData(
    0xebb6,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData send = IconData(
    0xe396,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData settings = IconData(
    0xe270,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData sparkles = IconData(
    0xe6a2,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData sun = IconData(
    0xe472,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData thumbsUp = IconData(
    0xe48e,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData ticket = IconData(
    0xe490,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData triangleAlert = IconData(
    0xe4e0,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData user = IconData(
    0xe4c2,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData userCheck = IconData(
    0xeafa,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData users = IconData(
    0xe4d6,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData video = IconData(
    0xe4da,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData wifiOff = IconData(
    0xe4f2,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData x = IconData(
    0xe4f6,
    fontFamily: _family,
    fontPackage: _package,
  );
}
