import 'dart:io';

import 'package:cc_natives/cc_natives.dart';
import 'package:flutter_test/flutter_test.dart';

/// Drift guard: the tree-sitter `.scm` extraction queries are embedded in
/// `cc_natives` (`embedded_queries.dart`, GENERATED by
/// `tool/gen_embedded_queries.dart`) as a compiled-in fallback; release
/// bundles also ship the canonical `scripts/natives/queries/*.scm` as real
/// files, which `GrammarManager.loadQuery` prefers. This test pins generated
/// Dart byte-identical to the canonical files, catching "edited the .scm but
/// forgot to regenerate" (and vice versa), and asserts every indexable
/// language resolves to an embedded query.
void main() {
  test('embedded tree-sitter queries match scripts/natives/queries/*.scm', () {
    final root = Directory.current.path;
    final queriesDir = Directory('$root/scripts/natives/queries');
    expect(queriesDir.existsSync(), isTrue, reason: 'run from the repo root');

    final onDisk = <String, String>{
      for (final f in queriesDir.listSync().whereType<File>())
        if (f.path.endsWith('.scm'))
          f.uri.pathSegments.last.replaceAll('.scm', ''): f.readAsStringSync(),
    };

    expect(
      embeddedTreeSitterQueries.keys.toSet(),
      onDisk.keys.toSet(),
      reason: 'embedded query ids must mirror scripts/natives/queries/',
    );
    for (final entry in onDisk.entries) {
      expect(
        embeddedTreeSitterQueries[entry.key],
        entry.value,
        reason:
            '${entry.key}.scm drifted from embedded_queries.dart — keep the '
            'Dart constant byte-identical to the canonical file',
      );
    }
  });

  test('every indexable language has an embedded query', () {
    for (final languageId in kLanguageByExtension.values.toSet()) {
      expect(
        embeddedTreeSitterQueries[queryIdFor(languageId)],
        isNotNull,
        reason:
            'language "$languageId" (query id '
            '"${queryIdFor(languageId)}") has no embedded query',
      );
    }
  });
}
