# Analyzer config for the cc_ui gallery app.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.directories.g.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    always_use_package_imports: true
    prefer_const_constructors: true
    prefer_single_quotes: true
