// GENERATED BY tool/gen_icon_seams.py — DO NOT EDIT.
// The icon constants below are self-documenting (name == glyph); per-field doc
// comments would be pure noise.
// ignore_for_file: public_member_api_docs
import 'package:flutter/widgets.dart';

/// Web-safe Phosphor icon set for the whole application.
///
/// The glyphs resolve against the Phosphor Regular font vendored by cc_ui
/// (`packages/cc_ui/fonts/Phosphor-Regular.ttf`), not an icon package. An
/// icon package exposes each style as a class of ~1530 `static const IconData`
/// fields; on Flutter web the dev compiler (DDC) lazily links a library the
/// first time one of its members is accessed, and linking that giant library
/// overflows the JS stack and crashes with a `StackOverflowError` before the
/// first frame renders (so `flutter run -d chrome` breaks even though a
/// dart2js release build is fine).
///
/// Declaring only the glyphs the app actually uses also keeps the icon
/// tree-shaker effective: the shipped font is a ~52 KB subset of the 489 KB
/// original. Generated by `tool/gen_icon_seams.py` — edit the mapping there,
/// never this file.
///
/// A ratchet in `test/core/lib_boundary_test.dart` forbids importing any
/// icon package into `lib/`.
@staticIconProvider
abstract final class AppIcons {
  static const String _family = 'PhosphorRegular';
  static const String _package = 'cc_ui';

  static const IconData activity = IconData(
    0xe000,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData alertCircle = IconData(
    0xe4e2,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData alertTriangle = IconData(
    0xe4e0,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData alignJustify = IconData(
    0xe482,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData appWindow = IconData(
    0xe5da,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData archive = IconData(
    0xe00c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData archiveRestore = IconData(
    0xe00e,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData arrowDown = IconData(
    0xe03e,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData arrowLeft = IconData(
    0xe058,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData arrowRight = IconData(
    0xe06c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData arrowUp = IconData(
    0xe08e,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData arrowUpRight = IconData(
    0xe092,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData atSign = IconData(
    0xe0ac,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData audioLines = IconData(
    0xe802,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData audioWaveform = IconData(
    0xe802,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData award = IconData(
    0xe320,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData ban = IconData(
    0xe32c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData barChart2 = IconData(
    0xe150,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData bell = IconData(
    0xe0ce,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData bellOff = IconData(
    0xe0d4,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData bold = IconData(
    0xe5be,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData bookMarked = IconData(
    0xe0ec,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData bookmark = IconData(
    0xe0ea,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData bookmarkCheck = IconData(
    0xe0ea,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData bot = IconData(
    0xe762,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData box = IconData(
    0xe390,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData boxes = IconData(
    0xe390,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData brain = IconData(
    0xe74e,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData bug = IconData(
    0xe5f4,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData building2 = IconData(
    0xe100,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData cable = IconData(
    0xeb5a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData calculator = IconData(
    0xe538,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData calendar = IconData(
    0xe108,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData calendarClock = IconData(
    0xe108,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData calendarDays = IconData(
    0xe108,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData calendarPlus = IconData(
    0xe714,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData calendarX = IconData(
    0xe10c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData caseSensitive = IconData(
    0xe6ee,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData chartColumn = IconData(
    0xe150,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData check = IconData(
    0xe182,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData checkCheck = IconData(
    0xe53a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData checkCircle = IconData(
    0xe184,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData checkCircle2 = IconData(
    0xe184,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData checkSquare = IconData(
    0xe186,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData chevronDown = IconData(
    0xe136,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData chevronLeft = IconData(
    0xe138,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData chevronRight = IconData(
    0xe13a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData chevronUp = IconData(
    0xe13c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData chevronsDown = IconData(
    0xe126,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData chevronsDownUp = IconData(
    0xe532,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData chevronsUpDown = IconData(
    0xe140,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData circle = IconData(
    0xe18a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData circleAlert = IconData(
    0xe4e2,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData circleCheck = IconData(
    0xe184,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData circleCheckBig = IconData(
    0xe184,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData circleDashed = IconData(
    0xe602,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData circleDot = IconData(
    0xe3ee,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData circleHelp = IconData(
    0xe3e8,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData circlePlay = IconData(
    0xe3d2,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData circleSlash = IconData(
    0xe32c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData circleStop = IconData(
    0xe46e,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData circleX = IconData(
    0xe4f8,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData clapperboard = IconData(
    0xe8c2,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData clipboard = IconData(
    0xe196,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData clock = IconData(
    0xe19a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData clock3 = IconData(
    0xe19a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData cloud = IconData(
    0xe1aa,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData cloudOff = IconData(
    0xe1b6,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData code = IconData(
    0xe1bc,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData columns = IconData(
    0xe546,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData columns3 = IconData(
    0xe546,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData command = IconData(
    0xe1c4,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData compass = IconData(
    0xe1c8,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData cookie = IconData(
    0xe6ca,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData copy = IconData(
    0xe1ca,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData cornerDownLeft = IconData(
    0xe044,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData cornerLeftDown = IconData(
    0xe04a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData cornerLeftUp = IconData(
    0xe04c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData cpu = IconData(
    0xe610,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData crosshair = IconData(
    0xe1d6,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData diff = IconData(
    0xe3d8,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData dollarSign = IconData(
    0xe550,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData dot = IconData(
    0xecde,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData download = IconData(
    0xe20c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData ellipsis = IconData(
    0xe1fe,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData externalLink = IconData(
    0xe5de,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData eye = IconData(
    0xe220,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData eyeOff = IconData(
    0xe224,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData factory = IconData(
    0xe760,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData file = IconData(
    0xe230,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData fileCode = IconData(
    0xe914,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData fileDiff = IconData(
    0xe27c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData fileEdit = IconData(
    0xe34c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData filePen = IconData(
    0xe34c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData filePlus = IconData(
    0xe236,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData fileQuestion = IconData(
    0xe704,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData fileText = IconData(
    0xe23a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData files = IconData(
    0xe710,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData filterX = IconData(
    0xe26c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData flag = IconData(
    0xe244,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData flame = IconData(
    0xe624,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData focus = IconData(
    0xe626,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData folder = IconData(
    0xe24a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData folderGit = IconData(
    0xe24a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData folderGit2 = IconData(
    0xe24a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData folderOpen = IconData(
    0xe256,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData folderTree = IconData(
    0xe260,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gauge = IconData(
    0xe628,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gem = IconData(
    0xe1ec,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gitBranch = IconData(
    0xe278,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gitCommit = IconData(
    0xe27a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gitCommitHorizontal = IconData(
    0xe27a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gitCompareArrows = IconData(
    0xe27c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gitFork = IconData(
    0xe27e,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gitMerge = IconData(
    0xe280,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gitPullRequest = IconData(
    0xe282,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gitPullRequestArrow = IconData(
    0xe282,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gitPullRequestClosed = IconData(
    0xe4f8,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gitPullRequestCreate = IconData(
    0xe282,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gitPullRequestDraft = IconData(
    0xe602,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData globe = IconData(
    0xe288,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gripVertical = IconData(
    0xeae2,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData hash = IconData(
    0xe2a2,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData heading = IconData(
    0xe6ba,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData image = IconData(
    0xe2ca,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData imageOff = IconData(
    0xe7a8,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData inbox = IconData(
    0xe4aa,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData info = IconData(
    0xe2ce,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData italic = IconData(
    0xe5c0,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData keyRound = IconData(
    0xe2d6,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData keyboard = IconData(
    0xe2d8,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData languages = IconData(
    0xe4a2,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData layoutDashboard = IconData(
    0xe464,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData layoutGrid = IconData(
    0xe296,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData layoutTemplate = IconData(
    0xe6d6,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData lightbulb = IconData(
    0xe2dc,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData link = IconData(
    0xe2e2,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData list = IconData(
    0xe2f0,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData listChecks = IconData(
    0xeadc,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData listFilter = IconData(
    0xe266,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData listTodo = IconData(
    0xeadc,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData loader = IconData(
    0xeb44,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData loaderCircle = IconData(
    0xeb44,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData lock = IconData(
    0xe2fa,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData logOut = IconData(
    0xe42a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData mapPin = IconData(
    0xe316,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData maximize2 = IconData(
    0xe1d0,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData medal = IconData(
    0xe320,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData menu = IconData(
    0xe2f0,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData messageCircle = IconData(
    0xe168,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData messageCircleQuestion = IconData(
    0xe168,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData messageSquare = IconData(
    0xe15c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData messageSquareCode = IconData(
    0xe15c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData messageSquareDashed = IconData(
    0xe15c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData messageSquarePlus = IconData(
    0xe15c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData messageSquareText = IconData(
    0xe17a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData messagesSquare = IconData(
    0xe17c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData mic = IconData(
    0xe326,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData micOff = IconData(
    0xe328,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData minus = IconData(
    0xe32a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData minusCircle = IconData(
    0xe32c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData monitor = IconData(
    0xe32e,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData moon = IconData(
    0xe330,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData moonStar = IconData(
    0xe58e,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData moreHorizontal = IconData(
    0xe1fe,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData move = IconData(
    0xe0a4,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData network = IconData(
    0xe67c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData newspaper = IconData(
    0xe344,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData notebook = IconData(
    0xe34e,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData notebookPen = IconData(
    0xe34e,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData notebookText = IconData(
    0xe34e,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData octagonAlert = IconData(
    0xe4e4,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData paintbrushVertical = IconData(
    0xe6f0,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData palette = IconData(
    0xe6c8,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData panelLeft = IconData(
    0xeab6,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData panelLeftClose = IconData(
    0xeab6,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData panelLeftOpen = IconData(
    0xeab6,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData panelRight = IconData(
    0xec24,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData pause = IconData(
    0xe39e,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData pauseCircle = IconData(
    0xe3a0,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData pencil = IconData(
    0xe3b4,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData pictureInPicture2 = IconData(
    0xe64c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData pin = IconData(
    0xe3e2,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData pinOff = IconData(
    0xe3e4,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData play = IconData(
    0xe3d0,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData plug = IconData(
    0xe946,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData plus = IconData(
    0xe3d4,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData power = IconData(
    0xe3da,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData puzzle = IconData(
    0xe596,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData quote = IconData(
    0xe660,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData radio = IconData(
    0xe77e,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData refreshCw = IconData(
    0xe036,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData regex = IconData(
    0xe0aa,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData repeat = IconData(
    0xe3f6,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData reply = IconData(
    0xe024,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData rocket = IconData(
    0xe3fc,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData rotateCcw = IconData(
    0xe038,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData rotateCw = IconData(
    0xe036,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData rss = IconData(
    0xe400,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData save = IconData(
    0xe248,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData scale = IconData(
    0xe750,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData scanEye = IconData(
    0xe220,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData scanSearch = IconData(
    0xebb6,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData scrollText = IconData(
    0xeb7a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData search = IconData(
    0xe30c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData searchX = IconData(
    0xe30e,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData send = IconData(
    0xe396,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData settings = IconData(
    0xe270,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData share2 = IconData(
    0xe408,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData shield = IconData(
    0xe40a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData shieldAlert = IconData(
    0xe412,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData shieldCheck = IconData(
    0xe40c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData shieldOff = IconData(
    0xe410,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData signalHigh = IconData(
    0xe144,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData skull = IconData(
    0xe916,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData slidersHorizontal = IconData(
    0xe434,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData smartphone = IconData(
    0xe1e0,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData smile = IconData(
    0xe436,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData sparkles = IconData(
    0xe6a2,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData square = IconData(
    0xe45e,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData squareCheck = IconData(
    0xe186,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData squareCheckBig = IconData(
    0xe186,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData squarePen = IconData(
    0xebc6,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData star = IconData(
    0xe46a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData sun = IconData(
    0xe472,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData tag = IconData(
    0xe478,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData target = IconData(
    0xe47c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData terminal = IconData(
    0xe47e,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData thumbsDown = IconData(
    0xe48c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData thumbsUp = IconData(
    0xe48e,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData ticket = IconData(
    0xe490,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData ticketCheck = IconData(
    0xe490,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData toggleLeft = IconData(
    0xe674,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData trash2 = IconData(
    0xe4a6,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData trendingUp = IconData(
    0xe4ae,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData triangleAlert = IconData(
    0xe4e0,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData trophy = IconData(
    0xe67e,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData type = IconData(
    0xe48a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData undo2 = IconData(
    0xe08a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData unlink = IconData(
    0xe2e4,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData unplug = IconData(
    0xeb56,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData upload = IconData(
    0xe4c0,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData user = IconData(
    0xe4c2,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData userCheck = IconData(
    0xeafa,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData userCog = IconData(
    0xe4cc,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData userMinus = IconData(
    0xe4ce,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData userPlus = IconData(
    0xe4d0,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData userRound = IconData(
    0xe4c4,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData users = IconData(
    0xe4d6,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData video = IconData(
    0xe4da,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData volume2 = IconData(
    0xe44a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData volumeOff = IconData(
    0xe45a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData wand = IconData(
    0xe6b6,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData workflow = IconData(
    0xe6ec,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData wrapText = IconData(
    0xea1e,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData wrench = IconData(
    0xe5d4,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData x = IconData(
    0xe4f6,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData xCircle = IconData(
    0xe4f8,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData zap = IconData(
    0xe2de,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData zapOff = IconData(
    0xe2e0,
    fontFamily: _family,
    fontPackage: _package,
  );
}
