// The icon constants below are self-documenting (name == glyph); per-field doc
// comments would be pure noise.
// ignore_for_file: public_member_api_docs
import 'package:flutter/widgets.dart';

/// Web-safe Lucide icon set for the whole application.
///
/// We deliberately do NOT import `package:lucide_icons_flutter/lucide_icons.dart`
/// anywhere in `lib/`. That package exposes its whole icon set as one
/// ~123k-line `LucideIcons` class of `static const IconData` fields. On Flutter
/// web the dev compiler (DDC) lazily links a library the first time one of its
/// members is accessed; linking that giant library overflows the JS stack and
/// crashes with a `StackOverflowError` before the first frame renders (so
/// `flutter run -d chrome` is broken even though a dart2js `--release` build
/// compiles fine).
///
/// Declaring only the glyphs the app actually uses keeps the same Lucide font
/// (still bundled via the `lucide_icons_flutter` dependency) without ever
/// triggering that initialization. Codepoints mirror `LucideIcons` (3.1.14+2)
/// and are extracted directly from the package, not hand-written. This is the
/// same mitigation `apps/cc_remote` uses; `lib/web_client/web_icons.dart`
/// re-exports this class so the web client and desktop share one icon table.
///
/// A ratchet in `test/core/lib_boundary_test.dart` forbids re-introducing a
/// `package:lucide_icons_flutter` import into `lib/`.
abstract final class AppIcons {
  static const String _family = 'Lucide';
  static const String _package = 'lucide_icons_flutter';

  static const IconData activity =
      IconData(57400, fontFamily: _family, fontPackage: _package);
  static const IconData alertCircle =
      IconData(57463, fontFamily: _family, fontPackage: _package);
  static const IconData alertTriangle =
      IconData(57747, fontFamily: _family, fontPackage: _package);
  static const IconData alignJustify =
      IconData(57732, fontFamily: _family, fontPackage: _package);
  static const IconData appWindow =
      IconData(58406, fontFamily: _family, fontPackage: _package);
  static const IconData archive =
      IconData(57409, fontFamily: _family, fontPackage: _package);
  static const IconData archiveRestore =
      IconData(58061, fontFamily: _family, fontPackage: _package);
  static const IconData arrowDown =
      IconData(57410, fontFamily: _family, fontPackage: _package);
  static const IconData arrowLeft =
      IconData(57416, fontFamily: _family, fontPackage: _package);
  static const IconData arrowRight =
      IconData(57417, fontFamily: _family, fontPackage: _package);
  static const IconData arrowUp =
      IconData(57418, fontFamily: _family, fontPackage: _package);
  static const IconData arrowUpRight =
      IconData(57421, fontFamily: _family, fontPackage: _package);
  static const IconData atSign =
      IconData(57422, fontFamily: _family, fontPackage: _package);
  static const IconData audioLines =
      IconData(58714, fontFamily: _family, fontPackage: _package);
  static const IconData audioWaveform =
      IconData(58715, fontFamily: _family, fontPackage: _package);
  static const IconData award =
      IconData(57423, fontFamily: _family, fontPackage: _package);
  static const IconData ban =
      IconData(57425, fontFamily: _family, fontPackage: _package);
  static const IconData barChart2 =
      IconData(57448, fontFamily: _family, fontPackage: _package);
  static const IconData bell =
      IconData(57433, fontFamily: _family, fontPackage: _package);
  static const IconData bellOff =
      IconData(57434, fontFamily: _family, fontPackage: _package);
  static const IconData bold =
      IconData(57437, fontFamily: _family, fontPackage: _package);
  static const IconData bookmark =
      IconData(57440, fontFamily: _family, fontPackage: _package);
  static const IconData bookmarkCheck =
      IconData(58655, fontFamily: _family, fontPackage: _package);
  static const IconData bot =
      IconData(57787, fontFamily: _family, fontPackage: _package);
  static const IconData box =
      IconData(57441, fontFamily: _family, fontPackage: _package);
  static const IconData boxes =
      IconData(58064, fontFamily: _family, fontPackage: _package);
  static const IconData brain =
      IconData(58310, fontFamily: _family, fontPackage: _package);
  static const IconData bug =
      IconData(57868, fontFamily: _family, fontPackage: _package);
  static const IconData building2 =
      IconData(58000, fontFamily: _family, fontPackage: _package);
  static const IconData cable =
      IconData(58595, fontFamily: _family, fontPackage: _package);
  static const IconData calendar =
      IconData(57443, fontFamily: _family, fontPackage: _package);
  static const IconData calendarClock =
      IconData(58116, fontFamily: _family, fontPackage: _package);
  static const IconData calendarDays =
      IconData(58041, fontFamily: _family, fontPackage: _package);
  static const IconData calendarPlus =
      IconData(58044, fontFamily: _family, fontPackage: _package);
  static const IconData calendarX =
      IconData(58046, fontFamily: _family, fontPackage: _package);
  static const IconData chartColumn =
      IconData(58019, fontFamily: _family, fontPackage: _package);
  static const IconData check =
      IconData(57452, fontFamily: _family, fontPackage: _package);
  static const IconData checkCheck =
      IconData(58254, fontFamily: _family, fontPackage: _package);
  static const IconData checkCircle =
      IconData(57468, fontFamily: _family, fontPackage: _package);
  static const IconData checkCircle2 =
      IconData(57894, fontFamily: _family, fontPackage: _package);
  static const IconData checkSquare =
      IconData(57706, fontFamily: _family, fontPackage: _package);
  static const IconData chevronDown =
      IconData(57453, fontFamily: _family, fontPackage: _package);
  static const IconData chevronLeft =
      IconData(57454, fontFamily: _family, fontPackage: _package);
  static const IconData chevronRight =
      IconData(57455, fontFamily: _family, fontPackage: _package);
  static const IconData chevronUp =
      IconData(57456, fontFamily: _family, fontPackage: _package);
  static const IconData chevronsDown =
      IconData(57457, fontFamily: _family, fontPackage: _package);
  static const IconData chevronsUpDown =
      IconData(57873, fontFamily: _family, fontPackage: _package);
  static const IconData circle =
      IconData(57462, fontFamily: _family, fontPackage: _package);
  static const IconData circleAlert =
      IconData(57463, fontFamily: _family, fontPackage: _package);
  static const IconData circleCheck =
      IconData(57894, fontFamily: _family, fontPackage: _package);
  static const IconData circleCheckBig =
      IconData(57468, fontFamily: _family, fontPackage: _package);
  static const IconData circleDashed =
      IconData(58544, fontFamily: _family, fontPackage: _package);
  static const IconData circleDot =
      IconData(58181, fontFamily: _family, fontPackage: _package);
  static const IconData circleHelp =
      IconData(57474, fontFamily: _family, fontPackage: _package);
  static const IconData circlePlay =
      IconData(57472, fontFamily: _family, fontPackage: _package);
  static const IconData circleSlash =
      IconData(58370, fontFamily: _family, fontPackage: _package);
  static const IconData circleStop =
      IconData(57475, fontFamily: _family, fontPackage: _package);
  static const IconData circleX =
      IconData(57476, fontFamily: _family, fontPackage: _package);
  static const IconData clapperboard =
      IconData(58011, fontFamily: _family, fontPackage: _package);
  static const IconData clipboard =
      IconData(57477, fontFamily: _family, fontPackage: _package);
  static const IconData clock =
      IconData(57479, fontFamily: _family, fontPackage: _package);
  static const IconData clock3 =
      IconData(57936, fontFamily: _family, fontPackage: _package);
  static const IconData cloud =
      IconData(57480, fontFamily: _family, fontPackage: _package);
  static const IconData cloudOff =
      IconData(57485, fontFamily: _family, fontPackage: _package);
  static const IconData code =
      IconData(57491, fontFamily: _family, fontPackage: _package);
  static const IconData columns =
      IconData(57496, fontFamily: _family, fontPackage: _package);
  static const IconData columns3 =
      IconData(57497, fontFamily: _family, fontPackage: _package);
  static const IconData compass =
      IconData(57499, fontFamily: _family, fontPackage: _package);
  static const IconData cookie =
      IconData(57963, fontFamily: _family, fontPackage: _package);
  static const IconData copy =
      IconData(57502, fontFamily: _family, fontPackage: _package);
  static const IconData cornerDownLeft =
      IconData(57505, fontFamily: _family, fontPackage: _package);
  static const IconData cornerLeftDown =
      IconData(57507, fontFamily: _family, fontPackage: _package);
  static const IconData cornerLeftUp =
      IconData(57508, fontFamily: _family, fontPackage: _package);
  static const IconData cpu =
      IconData(57513, fontFamily: _family, fontPackage: _package);
  static const IconData crosshair =
      IconData(57516, fontFamily: _family, fontPackage: _package);
  static const IconData diff =
      IconData(58124, fontFamily: _family, fontPackage: _package);
  static const IconData dot =
      IconData(58447, fontFamily: _family, fontPackage: _package);
  static const IconData download =
      IconData(57522, fontFamily: _family, fontPackage: _package);
  static const IconData ellipsis =
      IconData(57526, fontFamily: _family, fontPackage: _package);
  static const IconData externalLink =
      IconData(57529, fontFamily: _family, fontPackage: _package);
  static const IconData eye =
      IconData(57530, fontFamily: _family, fontPackage: _package);
  static const IconData eyeOff =
      IconData(57531, fontFamily: _family, fontPackage: _package);
  static const IconData factory =
      IconData(58015, fontFamily: _family, fontPackage: _package);
  static const IconData fileCode =
      IconData(57539, fontFamily: _family, fontPackage: _package);
  static const IconData fileDiff =
      IconData(58135, fontFamily: _family, fontPackage: _package);
  static const IconData fileEdit =
      IconData(58143, fontFamily: _family, fontPackage: _package);
  static const IconData filePen =
      IconData(58143, fontFamily: _family, fontPackage: _package);
  static const IconData filePlus =
      IconData(57545, fontFamily: _family, fontPackage: _package);
  static const IconData fileQuestion =
      IconData(58146, fontFamily: _family, fontPackage: _package);
  static const IconData fileText =
      IconData(57548, fontFamily: _family, fontPackage: _package);
  static const IconData files =
      IconData(57551, fontFamily: _family, fontPackage: _package);
  static const IconData filterX =
      IconData(58293, fontFamily: _family, fontPackage: _package);
  static const IconData flag =
      IconData(57553, fontFamily: _family, fontPackage: _package);
  static const IconData flame =
      IconData(57554, fontFamily: _family, fontPackage: _package);
  static const IconData focus =
      IconData(58014, fontFamily: _family, fontPackage: _package);
  static const IconData folder =
      IconData(57559, fontFamily: _family, fontPackage: _package);
  static const IconData folderGit =
      IconData(58377, fontFamily: _family, fontPackage: _package);
  static const IconData folderGit2 =
      IconData(58378, fontFamily: _family, fontPackage: _package);
  static const IconData folderOpen =
      IconData(57927, fontFamily: _family, fontPackage: _package);
  static const IconData folderTree =
      IconData(58172, fontFamily: _family, fontPackage: _package);
  static const IconData gauge =
      IconData(57791, fontFamily: _family, fontPackage: _package);
  static const IconData gem =
      IconData(57922, fontFamily: _family, fontPackage: _package);
  static const IconData gitBranch =
      IconData(57570, fontFamily: _family, fontPackage: _package);
  static const IconData gitCommit =
      IconData(57571, fontFamily: _family, fontPackage: _package);
  static const IconData gitCommitHorizontal =
      IconData(57571, fontFamily: _family, fontPackage: _package);
  static const IconData gitCompareArrows =
      IconData(58707, fontFamily: _family, fontPackage: _package);
  static const IconData gitFork =
      IconData(57997, fontFamily: _family, fontPackage: _package);
  static const IconData gitMerge =
      IconData(57572, fontFamily: _family, fontPackage: _package);
  static const IconData gitPullRequest =
      IconData(57573, fontFamily: _family, fontPackage: _package);
  static const IconData gitPullRequestArrow =
      IconData(58709, fontFamily: _family, fontPackage: _package);
  static const IconData gitPullRequestClosed =
      IconData(58202, fontFamily: _family, fontPackage: _package);
  static const IconData gitPullRequestCreate =
      IconData(58710, fontFamily: _family, fontPackage: _package);
  static const IconData gitPullRequestDraft =
      IconData(58203, fontFamily: _family, fontPackage: _package);
  static const IconData globe =
      IconData(57576, fontFamily: _family, fontPackage: _package);
  static const IconData gripVertical =
      IconData(57579, fontFamily: _family, fontPackage: _package);
  static const IconData hash =
      IconData(57583, fontFamily: _family, fontPackage: _package);
  static const IconData heading =
      IconData(58244, fontFamily: _family, fontPackage: _package);
  static const IconData image =
      IconData(57590, fontFamily: _family, fontPackage: _package);
  static const IconData imageOff =
      IconData(57792, fontFamily: _family, fontPackage: _package);
  static const IconData info =
      IconData(57593, fontFamily: _family, fontPackage: _package);
  static const IconData italic =
      IconData(57595, fontFamily: _family, fontPackage: _package);
  static const IconData keyRound =
      IconData(58531, fontFamily: _family, fontPackage: _package);
  static const IconData keyboard =
      IconData(57988, fontFamily: _family, fontPackage: _package);
  static const IconData languages =
      IconData(57598, fontFamily: _family, fontPackage: _package);
  static const IconData layoutDashboard =
      IconData(57793, fontFamily: _family, fontPackage: _package);
  static const IconData layoutGrid =
      IconData(57599, fontFamily: _family, fontPackage: _package);
  static const IconData layoutTemplate =
      IconData(57863, fontFamily: _family, fontPackage: _package);
  static const IconData lightbulb =
      IconData(57794, fontFamily: _family, fontPackage: _package);
  static const IconData link =
      IconData(57602, fontFamily: _family, fontPackage: _package);
  static const IconData list =
      IconData(57606, fontFamily: _family, fontPackage: _package);
  static const IconData listChecks =
      IconData(57808, fontFamily: _family, fontPackage: _package);
  static const IconData listTodo =
      IconData(58563, fontFamily: _family, fontPackage: _package);
  static const IconData loader =
      IconData(57609, fontFamily: _family, fontPackage: _package);
  static const IconData loaderCircle =
      IconData(57610, fontFamily: _family, fontPackage: _package);
  static const IconData lock =
      IconData(57611, fontFamily: _family, fontPackage: _package);
  static const IconData logOut =
      IconData(57614, fontFamily: _family, fontPackage: _package);
  static const IconData mapPin =
      IconData(57617, fontFamily: _family, fontPackage: _package);
  static const IconData maximize2 =
      IconData(57619, fontFamily: _family, fontPackage: _package);
  static const IconData medal =
      IconData(58223, fontFamily: _family, fontPackage: _package);
  static const IconData messageCircle =
      IconData(57622, fontFamily: _family, fontPackage: _package);
  static const IconData messageCircleQuestion =
      IconData(58728, fontFamily: _family, fontPackage: _package);
  static const IconData messageSquare =
      IconData(57623, fontFamily: _family, fontPackage: _package);
  static const IconData messageSquareCode =
      IconData(58732, fontFamily: _family, fontPackage: _package);
  static const IconData messageSquareDashed =
      IconData(58379, fontFamily: _family, fontPackage: _package);
  static const IconData messageSquarePlus =
      IconData(58380, fontFamily: _family, fontPackage: _package);
  static const IconData messageSquareText =
      IconData(58741, fontFamily: _family, fontPackage: _package);
  static const IconData messagesSquare =
      IconData(58381, fontFamily: _family, fontPackage: _package);
  static const IconData mic =
      IconData(57624, fontFamily: _family, fontPackage: _package);
  static const IconData micOff =
      IconData(57625, fontFamily: _family, fontPackage: _package);
  static const IconData minus =
      IconData(57628, fontFamily: _family, fontPackage: _package);
  static const IconData minusCircle =
      IconData(57470, fontFamily: _family, fontPackage: _package);
  static const IconData monitor =
      IconData(57629, fontFamily: _family, fontPackage: _package);
  static const IconData moon =
      IconData(57630, fontFamily: _family, fontPackage: _package);
  static const IconData moonStar =
      IconData(58384, fontFamily: _family, fontPackage: _package);
  static const IconData moreHorizontal =
      IconData(57526, fontFamily: _family, fontPackage: _package);
  static const IconData move =
      IconData(57633, fontFamily: _family, fontPackage: _package);
  static const IconData network =
      IconData(57637, fontFamily: _family, fontPackage: _package);
  static const IconData newspaper =
      IconData(58184, fontFamily: _family, fontPackage: _package);
  static const IconData notebook =
      IconData(58773, fontFamily: _family, fontPackage: _package);
  static const IconData notebookPen =
      IconData(58774, fontFamily: _family, fontPackage: _package);
  static const IconData notebookText =
      IconData(58776, fontFamily: _family, fontPackage: _package);
  static const IconData octagonAlert =
      IconData(57639, fontFamily: _family, fontPackage: _package);
  static const IconData paintbrushVertical =
      IconData(58088, fontFamily: _family, fontPackage: _package);
  static const IconData pause =
      IconData(57646, fontFamily: _family, fontPackage: _package);
  static const IconData pauseCircle =
      IconData(57471, fontFamily: _family, fontPackage: _package);
  static const IconData pencil =
      IconData(57849, fontFamily: _family, fontPackage: _package);
  static const IconData pictureInPicture2 =
      IconData(58287, fontFamily: _family, fontPackage: _package);
  static const IconData play =
      IconData(57660, fontFamily: _family, fontPackage: _package);
  static const IconData plug =
      IconData(58239, fontFamily: _family, fontPackage: _package);
  static const IconData plus =
      IconData(57661, fontFamily: _family, fontPackage: _package);
  static const IconData power =
      IconData(57664, fontFamily: _family, fontPackage: _package);
  static const IconData puzzle =
      IconData(58012, fontFamily: _family, fontPackage: _package);
  static const IconData quote =
      IconData(57913, fontFamily: _family, fontPackage: _package);
  static const IconData radio =
      IconData(57666, fontFamily: _family, fontPackage: _package);
  static const IconData refreshCw =
      IconData(57669, fontFamily: _family, fontPackage: _package);
  static const IconData repeat =
      IconData(57670, fontFamily: _family, fontPackage: _package);
  static const IconData rocket =
      IconData(57990, fontFamily: _family, fontPackage: _package);
  static const IconData rotateCcw =
      IconData(57672, fontFamily: _family, fontPackage: _package);
  static const IconData rss =
      IconData(57674, fontFamily: _family, fontPackage: _package);
  static const IconData save =
      IconData(57677, fontFamily: _family, fontPackage: _package);
  static const IconData scale =
      IconData(57874, fontFamily: _family, fontPackage: _package);
  static const IconData scanEye =
      IconData(58678, fontFamily: _family, fontPackage: _package);
  static const IconData scanSearch =
      IconData(58679, fontFamily: _family, fontPackage: _package);
  static const IconData scrollText =
      IconData(58463, fontFamily: _family, fontPackage: _package);
  static const IconData search =
      IconData(57681, fontFamily: _family, fontPackage: _package);
  static const IconData searchX =
      IconData(58541, fontFamily: _family, fontPackage: _package);
  static const IconData send =
      IconData(57682, fontFamily: _family, fontPackage: _package);
  static const IconData settings =
      IconData(57684, fontFamily: _family, fontPackage: _package);
  static const IconData share2 =
      IconData(57686, fontFamily: _family, fontPackage: _package);
  static const IconData shield =
      IconData(57688, fontFamily: _family, fontPackage: _package);
  static const IconData shieldAlert =
      IconData(57854, fontFamily: _family, fontPackage: _package);
  static const IconData shieldCheck =
      IconData(57855, fontFamily: _family, fontPackage: _package);
  static const IconData shieldOff =
      IconData(57690, fontFamily: _family, fontPackage: _package);
  static const IconData signalHigh =
      IconData(57952, fontFamily: _family, fontPackage: _package);
  static const IconData skull =
      IconData(57889, fontFamily: _family, fontPackage: _package);
  static const IconData slidersHorizontal =
      IconData(58010, fontFamily: _family, fontPackage: _package);
  static const IconData smartphone =
      IconData(57699, fontFamily: _family, fontPackage: _package);
  static const IconData smile =
      IconData(57700, fontFamily: _family, fontPackage: _package);
  static const IconData sparkles =
      IconData(58386, fontFamily: _family, fontPackage: _package);
  static const IconData square =
      IconData(57703, fontFamily: _family, fontPackage: _package);
  static const IconData squareCheck =
      IconData(58713, fontFamily: _family, fontPackage: _package);
  static const IconData squarePen =
      IconData(57714, fontFamily: _family, fontPackage: _package);
  static const IconData star =
      IconData(57718, fontFamily: _family, fontPackage: _package);
  static const IconData sun =
      IconData(57720, fontFamily: _family, fontPackage: _package);
  static const IconData tag =
      IconData(57727, fontFamily: _family, fontPackage: _package);
  static const IconData terminal =
      IconData(57729, fontFamily: _family, fontPackage: _package);
  static const IconData ticket =
      IconData(57871, fontFamily: _family, fontPackage: _package);
  static const IconData ticketCheck =
      IconData(58798, fontFamily: _family, fontPackage: _package);
  static const IconData toggleLeft =
      IconData(57739, fontFamily: _family, fontPackage: _package);
  static const IconData trash2 =
      IconData(57742, fontFamily: _family, fontPackage: _package);
  static const IconData trendingUp =
      IconData(57745, fontFamily: _family, fontPackage: _package);
  static const IconData triangleAlert =
      IconData(57747, fontFamily: _family, fontPackage: _package);
  static const IconData trophy =
      IconData(58227, fontFamily: _family, fontPackage: _package);
  static const IconData type =
      IconData(57752, fontFamily: _family, fontPackage: _package);
  static const IconData unlink =
      IconData(57756, fontFamily: _family, fontPackage: _package);
  static const IconData unplug =
      IconData(58461, fontFamily: _family, fontPackage: _package);
  static const IconData upload =
      IconData(57758, fontFamily: _family, fontPackage: _package);
  static const IconData user =
      IconData(57759, fontFamily: _family, fontPackage: _package);
  static const IconData userCheck =
      IconData(57760, fontFamily: _family, fontPackage: _package);
  static const IconData userPlus =
      IconData(57762, fontFamily: _family, fontPackage: _package);
  static const IconData userRound =
      IconData(58472, fontFamily: _family, fontPackage: _package);
  static const IconData users =
      IconData(57764, fontFamily: _family, fontPackage: _package);
  static const IconData video =
      IconData(57765, fontFamily: _family, fontPackage: _package);
  static const IconData volume2 =
      IconData(57771, fontFamily: _family, fontPackage: _package);
  static const IconData volumeOff =
      IconData(58918, fontFamily: _family, fontPackage: _package);
  static const IconData wand =
      IconData(57926, fontFamily: _family, fontPackage: _package);
  static const IconData workflow =
      IconData(58405, fontFamily: _family, fontPackage: _package);
  static const IconData wrapText =
      IconData(57928, fontFamily: _family, fontPackage: _package);
  static const IconData wrench =
      IconData(57777, fontFamily: _family, fontPackage: _package);
  static const IconData x =
      IconData(57778, fontFamily: _family, fontPackage: _package);
  static const IconData xCircle =
      IconData(57476, fontFamily: _family, fontPackage: _package);
  static const IconData zap =
      IconData(57780, fontFamily: _family, fontPackage: _package);
  static const IconData zapOff =
      IconData(57781, fontFamily: _family, fontPackage: _package);
}
