// Regenerates packages/cc_markdown/lib/src/parser/emoji_shortcodes.dart — the
// `:shortcode:` → emoji table the inline parser resolves against — from
// gemoji, the database GitHub itself renders comment bodies with:
//
//   https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json
//
// Usage (from the repo root):
//   fvm dart run tool/gen_emoji_shortcodes.dart
//
// Same discipline as tool/gen_geoip_country.dart: run the generator, commit
// the regenerated Dart file alongside. The table rides inside the parser
// (cc_markdown is web-safe and has no asset loader), so it must be source.
//
// Two deliberate omissions, both invisible in the output:
//   * GitHub's ~23 CUSTOM shortcodes (`:octocat:`, `:shipit:`, `:rage1:` …)
//     are images, not characters — https://api.github.com/emojis serves them
//     from a non-`/unicode/` path. There is nothing to substitute, so they
//     stay literal text exactly as they do in any non-GitHub renderer.
//   * Skin-tone and other modifier sequences have no gemoji alias, so they
//     are unreachable by shortcode on GitHub too.
//
// The `emoji` field is read verbatim rather than derived from the emoji image
// URL: the URL's codepoint list DROPS the U+FE0F variation selector
// (`:one:` is served as `0031-20e3`), which renders the keycap as a bare "1"
// on a font that needs the selector to switch to emoji presentation.

import 'dart:collection';
import 'dart:convert';
import 'dart:io';

const _sourceUrl =
    'https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json';

const _outPath = 'packages/cc_markdown/lib/src/parser/emoji_shortcodes.dart';

/// gemoji's alias grammar (and therefore GitHub's): lowercase only.
final RegExp _aliasPattern = RegExp(r'^[a-z0-9_+-]+$');

Future<void> main() async {
  final body = await _download(_sourceUrl);
  final decoded = jsonDecode(body);
  if (decoded is! List || decoded.isEmpty) {
    _fail('expected a non-empty JSON array at $_sourceUrl');
  }

  // Sorted so the generated file diffs line-by-line across regenerations
  // instead of reshuffling whenever gemoji reorders its database.
  final table = SplayTreeMap<String, String>();
  for (final entry in decoded) {
    if (entry is! Map) {
      _fail('malformed record: $entry');
    }
    final emoji = entry['emoji'];
    final aliases = entry['aliases'];
    if (emoji is! String || emoji.isEmpty || aliases is! List) {
      continue;
    }
    if (emoji.contains(' ') || emoji.contains('\n')) {
      _fail('emoji "$emoji" contains a packing separator');
    }
    for (final alias in aliases) {
      if (alias is! String || !_aliasPattern.hasMatch(alias)) {
        _fail('alias "$alias" is outside the [a-z0-9_+-] grammar');
      }
      final previous = table[alias];
      if (previous != null && previous != emoji) {
        _fail('alias "$alias" maps to both "$previous" and "$emoji"');
      }
      table[alias] = emoji;
    }
  }

  if (table.length < 1500) {
    _fail(
      'only ${table.length} shortcodes parsed — refusing to emit a table that '
      'small (the GitHub set is ~1900).',
    );
  }
  final longest = table.keys
      .map((k) => k.length)
      .reduce((a, b) => a > b ? a : b);
  stdout.writeln('parsed ${table.length} shortcodes, longest name $longest');

  final out = StringBuffer()
    ..writeln('// GENERATED FILE — DO NOT EDIT BY HAND.')
    ..writeln('//')
    ..writeln('// Generated by `tool/gen_emoji_shortcodes.dart` from gemoji,')
    ..writeln('// the database GitHub renders comment bodies with (MIT):')
    ..writeln('//')
    ..writeln('//   $_sourceUrl')
    ..writeln('//')
    ..writeln('// To refresh the table, run:')
    ..writeln('//')
    ..writeln('//   fvm dart run tool/gen_emoji_shortcodes.dart')
    ..writeln('//')
    ..writeln('// and commit this file.')
    ..writeln('//')
    ..writeln("// GitHub's custom image shortcodes (`:octocat:`, `:shipit:`)")
    ..writeln('// are absent on purpose: they are images, not characters, so')
    ..writeln('// they stay literal text.')
    ..writeln('//')
    ..writeln('// Regenerated: ${DateTime.now().toUtc().toIso8601String()}')
    ..writeln()
    ..writeln('/// Longest shortcode name in [_packed], so the inline scanner')
    ..writeln(
      '/// can bound its look-ahead: a `:` with no closing colon inside',
    )
    ..writeln('/// this many characters is punctuation, not a shortcode.')
    ..writeln('const int kCcMaxEmojiShortcodeLength = $longest;')
    ..writeln()
    ..writeln('/// The number of shortcodes in [_packed]. Pinned by a test so')
    ..writeln('/// a truncated regeneration cannot land unnoticed.')
    ..writeln('const int kCcEmojiShortcodeCount = ${table.length};')
    ..writeln()
    ..writeln('/// `name<space>emoji` records separated by newlines — NOT a')
    ..writeln('/// const map. A const map literal is an `_ImmutableMap`, whose')
    ..writeln('/// lookup is a LINEAR scan of its key/value pairs, so every')
    ..writeln('/// `:` in a document would cost up to ${table.length} string')
    ..writeln('/// comparisons. Unpacked once into [_table] instead, which is')
    ..writeln('/// a real hash map, and only when a document actually contains')
    ..writeln('/// a candidate shortcode.')
    ..writeln('///')
    ..writeln('/// Neither separator can occur inside a record: names are')
    ..writeln('/// `[a-z0-9_+-]+` and no emoji sequence contains a space or a')
    ..writeln('/// newline (the generator asserts both).')
    ..writeln('const String _packed =');

  final entries = table.entries.toList();
  for (var i = 0; i < entries.length; i++) {
    final last = i == entries.length - 1;
    // One record per literal: a line break inside a surrogate pair would make
    // the file invalid UTF-8, and one-per-line keeps regeneration diffable.
    out.writeln(
      "    '${entries[i].key} ${entries[i].value}${last ? '' : r'\n'}'"
      '${last ? ';' : ''}',
    );
  }

  out
    ..writeln()
    ..writeln('Map<String, String>? _cache;')
    ..writeln()
    ..writeln('Map<String, String> get _table => _cache ??= _unpack();')
    ..writeln()
    ..writeln('Map<String, String> _unpack() {')
    ..writeln('  final table = <String, String>{};')
    ..writeln(r"  for (final record in _packed.split('\n')) {")
    ..writeln(r"    final space = record.indexOf(' ');")
    ..writeln(
      '    table[record.substring(0, space)] = '
      'record.substring(space + 1);',
    )
    ..writeln('  }')
    ..writeln('  return table;')
    ..writeln('}')
    ..writeln()
    ..writeln('/// The emoji for GitHub shortcode [name] (given WITHOUT its')
    ..writeln('/// surrounding colons), or null when [name] is not one — which')
    ..writeln('/// includes GitHub\'s custom image emoji. Case-sensitive,')
    ..writeln('/// matching gemoji: `:Smile:` is not `:smile:`.')
    ..writeln('String? ccEmojiForShortcode(String name) => _table[name];')
    ..writeln()
    ..writeln('/// Every known shortcode name. For callers that offer')
    ..writeln('/// completion over the set rather than resolving one name.')
    ..writeln('Iterable<String> get ccEmojiShortcodeNames => _table.keys;');

  File(_outPath).writeAsStringSync(out.toString());
  stdout.writeln('wrote $_outPath');
}

/// Downloads [url] once, retrying ONE time; any further failure is fatal —
/// a partial table must never ship silently.
Future<String> _download(String url) async {
  Object? lastError;
  for (var attempt = 1; attempt <= 2; attempt++) {
    final client = HttpClient()
      ..connectionTimeout = const Duration(seconds: 30);
    try {
      final request = await client.getUrl(Uri.parse(url));
      final response = await request.close().timeout(
        const Duration(seconds: 60),
      );
      if (response.statusCode != HttpStatus.ok) {
        throw HttpException('HTTP ${response.statusCode}', uri: Uri.parse(url));
      }
      return await utf8.decoder.bind(response).join();
    } catch (e) {
      lastError = e;
      stderr.writeln('download attempt $attempt failed: $e');
      if (attempt == 1) {
        stderr.writeln('retrying once…');
        await Future<void>.delayed(const Duration(seconds: 2));
      }
    } finally {
      client.close(force: true);
    }
  }
  _fail('could not download the emoji database from $url: $lastError');
}

Never _fail(String message) {
  stderr.writeln('gen_emoji_shortcodes: $message');
  exit(1);
}
