// Generates the demo server's compiled-in fixtures from authored JSON.
//
// Run: fvm dart run tool/gen_demo_fixtures.dart
//
// WHY the fixtures compile into the binary rather than shipping beside it:
// `dart build cli` produces a self-contained bundle, and a demo that only has
// its data when a sibling directory happens to exist fails as an EMPTY demo —
// the worst failure shape, because it looks like it booted fine.
//
// The generator deliberately emits the JSON verbatim as a Dart string rather
// than generating object literals: the parsing already exists
// (`DemoRunScript.fromJson`, which validates and rejects unknown step kinds),
// so generating code that reproduces it would be a second thing to keep right.
//
// Same discipline as `tool/gen_workers.sh` + `test/tooling/web_workers_test.dart`:
// the generated file is COMMITTED, and a test byte-diffs it so a stale fixture
// fails CI instead of silently shipping yesterday's demo.
import 'dart:convert';
import 'dart:io';

void main(List<String> args) {
  final repoRoot = Directory.current.path;
  final sourceDir = Directory('$repoRoot/packages/cc_server_core/demo_fixtures');
  if (!sourceDir.existsSync()) {
    stderr.writeln('gen_demo_fixtures: ${sourceDir.path} not found');
    exit(2);
  }

  final generated = render(sourceDir);
  final output = File(
    '$repoRoot/packages/cc_server_core/lib/src/demo/fixtures/demo_fixtures.g.dart',
  );
  final check = args.contains('--check');

  if (check) {
    final current = output.existsSync() ? output.readAsStringSync() : '';
    if (current != generated) {
      stderr.writeln(
        'gen_demo_fixtures: ${output.path} is STALE.\n'
        'Run: fvm dart run tool/gen_demo_fixtures.dart',
      );
      exit(1);
    }
    stdout.writeln('gen_demo_fixtures: up to date');
    return;
  }

  output.parent.createSync(recursive: true);
  output.writeAsStringSync(generated);
  stdout.writeln('gen_demo_fixtures: wrote ${output.path}');
}

/// Renders the generated Dart source for the fixtures under [sourceDir].
String render(Directory sourceDir) {
  final runs = _readJsonDir(Directory('${sourceDir.path}/runs'));
  final pullRequests = _decode(File('${sourceDir.path}/pull_requests.json'));
  final logo = File('${sourceDir.path}/parced.png');
  final logoBase64 = logo.existsSync()
      ? base64Encode(logo.readAsBytesSync())
      : '';
  final buffer = StringBuffer()
    ..writeln('// GENERATED BY tool/gen_demo_fixtures.dart — DO NOT EDIT.')
    ..writeln('//')
    ..writeln('// Source: packages/cc_server_core/demo_fixtures/')
    ..writeln('// Regenerate: fvm dart run tool/gen_demo_fixtures.dart')
    ..writeln('library;')
    ..writeln()
    ..writeln('/// The demo\'s agent-run scripts, as authored JSON.')
    ..writeln('///')
    ..writeln('/// Parsed by `DemoRunScript.fromJson`, which rejects an unknown')
    ..writeln('/// step kind — so a malformed fixture fails loudly at boot')
    ..writeln('/// rather than dropping a beat from a run.')
    ..writeln('const String kDemoRunScriptsJson = ${_dartString(jsonEncode(runs))};')
    ..writeln()
    ..writeln('/// The demo\'s pull-request world, in the SAME shape the')
    ..writeln('/// production PR cache stores (see `PrCacheCodec.*ToCache`), so')
    ..writeln('/// a fixture is a realistic cache entry rather than a parallel')
    ..writeln('/// invention. Timestamps are `@-<n><unit>` markers the seeder')
    ..writeln('/// resolves against the clock at seed time.')
    ..writeln('const String kDemoPullRequestsJson = ${_dartString(jsonEncode(pullRequests))};')
    ..writeln()
    ..writeln('/// The demo workspace\'s logo (PNG), base64. The seeder writes it')
    ..writeln('/// to `<dataDir>/<workspaceId>/logo.png` and points the workspace')
    ..writeln('/// row\'s `logo_path` at it, so `/workspace/logo` serves the brand')
    ..writeln('/// with no outbound fetch. Empty when `parced.png` is missing — the')
    ..writeln('/// client then renders initials, same as any logo-less workspace.')
    ..writeln('const String kDemoLogoBase64 = ${_dartString(logoBase64)};');
  return buffer.toString();
}

/// Reads every `*.json` in [dir], sorted by filename for a stable output.
List<dynamic> _readJsonDir(Directory dir) {
  if (!dir.existsSync()) {
    return const [];
  }
  final files =
      dir.listSync().whereType<File>().where((f) => f.path.endsWith('.json')).toList()
        ..sort((a, b) => a.path.compareTo(b.path));
  return [
    for (final file in files) _decode(file),
  ];
}

dynamic _decode(File file) {
  try {
    return jsonDecode(file.readAsStringSync());
  } on FormatException catch (e) {
    stderr.writeln('gen_demo_fixtures: ${file.path} is not valid JSON: $e');
    exit(2);
  }
}

/// Encodes [value] as a Dart double-quoted string literal.
///
/// `jsonEncode` gets the quoting and the control-character escapes right, but
/// it does NOT escape `$` — which Dart would then treat as interpolation, so a
/// fixture containing `$foo` would fail to compile (or worse, compile into
/// something else).
String _dartString(String value) {
  final json = jsonEncode(value);
  return json.replaceAll(r'$', r'\$');
}
