// Bakes `assets/browser_logos/<engine>_color.svg` into the Dart consts the rig
// guest's own new-tab page inlines.
//
//   fvm dart run tool/gen_browser_marks.dart
//
// A browser rig's welcome page is written INTO a VM, so it cannot read a
// Flutter asset — the artwork has to exist as a string too. Maintaining that
// string by hand is how the boot screen and the page it settles into came to
// show different logos, so the assets are the source and this writes the
// string. `test/features/rigs/presentation/browser_logo_assets_test.dart`
// re-derives the same bytes and fails when the two drift.
library;

import 'dart:io';

import 'package:cc_domain/features/rigs/domain/value_objects/browser_mark_inlining.dart';
import 'package:cc_domain/features/rigs/domain/value_objects/rig_browser_engine.dart';

const _output =
    'packages/cc_domain/lib/features/rigs/domain/value_objects/'
    'browser_engine_marks.dart';

void main(List<String> args) {
  final check = args.contains('--check');
  final buffer = StringBuffer()
    ..writeln('// GENERATED BY tool/gen_browser_marks.dart — DO NOT EDIT.')
    ..writeln('//')
    ..writeln('// Source: assets/browser_logos/<engine>_color.svg. Edit the')
    ..writeln('// SVG, then re-run the generator.')
    ..writeln('// ignore_for_file: public_member_api_docs')
    ..writeln('library;')
    ..writeln();
  for (final engine in RigBrowserEngine.values) {
    final file = File('assets/browser_logos/${engine.wire}_color.svg');
    if (!file.existsSync()) {
      stderr.writeln('missing ${file.path}');
      exit(1);
    }
    final String mark;
    try {
      mark = inlineBrowserMark(file.readAsStringSync());
    } on FormatException catch (e) {
      stderr.writeln('${file.path}: ${e.message}');
      exit(1);
    }
    buffer
      ..writeln('const String ${engine.wire}EngineMark =')
      ..writeln(_literal(mark))
      ..writeln();
  }
  final generated = buffer.toString();
  final out = File(_output);
  final current = out.existsSync() ? out.readAsStringSync() : '';
  if (check) {
    if (current != generated) {
      stderr.writeln('$_output is stale — run tool/gen_browser_marks.dart');
      exit(1);
    }
    stdout.writeln('$_output is up to date');
    return;
  }
  out.writeAsStringSync(generated);
  stdout.writeln('wrote $_output');
}

/// Wraps [mark] as an adjacent-string Dart literal that fits the line limit.
String _literal(String mark) {
  const width = 68;
  final chunks = <String>[];
  for (var i = 0; i < mark.length; i += width) {
    chunks.add(mark.substring(i, min(i + width, mark.length)));
  }
  return [
    for (var i = 0; i < chunks.length; i++)
      "    '${chunks[i]}'${i == chunks.length - 1 ? ';' : ''}",
  ].join('\n');
}

int min(int a, int b) => a < b ? a : b;
