#!/usr/bin/env python3
"""Generates the embedded bitmap font snapcompact rasterizes with.

Rasterizes printable ASCII from a real monospace face into a column-major
1-bit table and emits it as a Dart const. Run when the cell size or the source
face changes; the output is committed, so neither the build nor the server
needs PIL or a font file.

    python3 tool/gen_glyph_font.py > packages/cc_infra/lib/src/context/glyph_font.dart
"""
import sys
from PIL import Image, ImageDraw, ImageFont

CELL_W, CELL_H, BASELINE = 5, 9, 7
FIRST, LAST = 32, 126
FACE, SIZE = "/System/Library/Fonts/Menlo.ttc", 8
# Anti-aliasing at this size turns every stem into a grey smear; the threshold
# is where a stem still reads as a stem and a hairline serif does not become a
# stray pixel.
THRESHOLD = 100


def glyph(font, char):
    img = Image.new("L", (CELL_W, CELL_H), 0)
    # Baseline-anchored so ascenders and descenders land in the same rows for
    # every glyph — otherwise `g` and `o` sit at different heights and a line
    # of text visibly wobbles.
    ImageDraw.Draw(img).text((0, BASELINE), char, font=font, fill=255, anchor="ls")
    cols = []
    for x in range(CELL_W):
        bits = 0
        for y in range(CELL_H):
            if img.getpixel((x, y)) >= THRESHOLD:
                bits |= 1 << y
        cols.append(bits)
    return cols


def main():
    font = ImageFont.truetype(FACE, SIZE)
    out = sys.stdout
    out.write(f'''// GENERATED by tool/gen_glyph_font.py — do not edit by hand.
//
// A {CELL_W}x{CELL_H} bitmap font for printable ASCII, column-major: entry `i`
// covers code point `kGlyphFirst + i`, byte `x` is column `x`, and bit `y` of
// that byte is the pixel at row `y`.
//
// **Why the font is a table and not a font file.** snapcompact runs on the
// server, which has no Flutter engine and therefore no text rasterizer.
// Loading a TTF would mean a font dependency, a file to ship, and a failure
// mode where compaction stops working because an asset moved. At this size the
// whole printable range is under a kilobyte of const data — smaller than the
// code that would load a file.

/// Width of one glyph cell, in pixels.
const int kGlyphWidth = {CELL_W};

/// Height of one glyph cell, in pixels. Includes the descender row.
const int kGlyphHeight = {CELL_H};

/// The first ASCII code point the font covers.
const int kGlyphFirst = {FIRST};

/// The last ASCII code point the font covers.
const int kGlyphLast = {LAST};

/// Column bitmaps for code points [kGlyphFirst]..[kGlyphLast].
const List<List<int>> kGlyphColumns = [
''')
    for code in range(FIRST, LAST + 1):
        cols = glyph(font, chr(code))
        label = chr(code).replace('\\\\', '\\\\\\\\')
        out.write(
            f"  [{', '.join(f'0x{c:03X}' for c in cols)}], // {code} {label}\n"
        )
    out.write('];\n')


main()
