// Mocks generated by Mockito 5.4.6 from annotations
// in control_center/test/features/pr_review/data/repositories/mock_spec.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:control_center/core/database/app_database.dart' as _i2;
import 'package:control_center/core/database/daos/cache_dao.dart' as _i5;
import 'package:control_center/core/database/daos/review_dao.dart' as _i7;
import 'package:control_center/core/network/github_api_client.dart' as _i15;
import 'package:control_center/core/network/github_content_client.dart' as _i10;
import 'package:control_center/core/network/github_graphql_client.dart' as _i9;
import 'package:control_center/core/network/github_pr_client.dart' as _i8;
import 'package:control_center/core/network/models/github_check_run.dart'
    as _i21;
import 'package:control_center/core/network/models/github_commit.dart' as _i19;
import 'package:control_center/core/network/models/github_issue_comment.dart'
    as _i20;
import 'package:control_center/core/network/models/github_pull_request.dart'
    as _i17;
import 'package:control_center/core/network/models/github_pull_request_file.dart'
    as _i18;
import 'package:control_center/core/network/models/github_reaction.dart'
    as _i13;
import 'package:control_center/core/network/models/github_review.dart' as _i12;
import 'package:control_center/core/network/models/github_review_comment.dart'
    as _i11;
import 'package:control_center/core/network/models/github_user.dart' as _i23;
import 'package:control_center/core/network/models/github_workflow_run.dart'
    as _i22;
import 'package:dio/dio.dart' as _i16;
import 'package:drift/drift.dart' as _i3;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_1 extends _i1.SmartFake
    implements _i3.DatabaseConnection {
  _FakeDatabaseConnection_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_2 extends _i1.SmartFake
    implements _i3.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_3 extends _i1.SmartFake implements _i3.QueryExecutor {
  _FakeQueryExecutor_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_4 extends _i1.SmartFake
    implements _i4.StreamQueryStore {
  _FakeStreamQueryStore_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_5 extends _i1.SmartFake
    implements _i3.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$CachesTableTable_6 extends _i1.SmartFake
    implements _i2.$CachesTableTable {
  _Fake$CachesTableTable_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCacheDaoManager_7 extends _i1.SmartFake
    implements _i5.CacheDaoManager {
  _FakeCacheDaoManager_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_8<T1> extends _i1.SmartFake implements _i6.Future<T1> {
  _FakeFuture_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_9<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.InsertStatement<T1, D1> {
  _FakeInsertStatement_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_10<T extends _i3.Table, D> extends _i1.SmartFake
    implements _i3.UpdateStatement<T, D> {
  _FakeUpdateStatement_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_11<T1 extends _i3.HasResultSet, D>
    extends _i1.SmartFake
    implements _i3.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_12<FirstT extends _i3.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i3.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_13<Row> extends _i1.SmartFake
    implements _i3.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_14<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_15<T> extends _i1.SmartFake implements _i3.Selectable<T> {
  _FakeSelectable_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_16 extends _i1.SmartFake
    implements _i3.GenerationContext {
  _FakeGenerationContext_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ReviewDraftsTable_17 extends _i1.SmartFake
    implements _i2.$ReviewDraftsTable {
  _Fake$ReviewDraftsTable_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReviewDaoManager_18 extends _i1.SmartFake
    implements _i7.ReviewDaoManager {
  _FakeReviewDaoManager_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGitHubPrClient_19 extends _i1.SmartFake
    implements _i8.GitHubPrClient {
  _FakeGitHubPrClient_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGitHubGraphQLClient_20 extends _i1.SmartFake
    implements _i9.GitHubGraphQLClient {
  _FakeGitHubGraphQLClient_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGitHubContentClient_21 extends _i1.SmartFake
    implements _i10.GitHubContentClient {
  _FakeGitHubContentClient_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginatedPullRequests_22 extends _i1.SmartFake
    implements _i8.PaginatedPullRequests {
  _FakePaginatedPullRequests_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGitHubReviewComment_23 extends _i1.SmartFake
    implements _i11.GitHubReviewComment {
  _FakeGitHubReviewComment_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGitHubReview_24 extends _i1.SmartFake implements _i12.GitHubReview {
  _FakeGitHubReview_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGitHubReaction_25 extends _i1.SmartFake
    implements _i13.GitHubReaction {
  _FakeGitHubReaction_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CacheDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheDao extends _i1.Mock implements _i5.CacheDao {
  @override
  _i2.AppDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeAppDatabase_0(
              this,
              Invocation.getter(#attachedDatabase),
            ),
            returnValueForMissingStub: _FakeAppDatabase_0(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i2.AppDatabase);

  @override
  _i3.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_1(
              this,
              Invocation.getter(#connection),
            ),
            returnValueForMissingStub: _FakeDatabaseConnection_1(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i3.DatabaseConnection);

  @override
  _i3.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_2(
              this,
              Invocation.getter(#options),
            ),
            returnValueForMissingStub: _FakeDriftDatabaseOptions_2(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i3.DriftDatabaseOptions);

  @override
  _i3.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i14.dummyValue<_i3.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
            returnValueForMissingStub: _i14.dummyValue<_i3.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i3.SqlTypes);

  @override
  _i3.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_3(
              this,
              Invocation.getter(#executor),
            ),
            returnValueForMissingStub: _FakeQueryExecutor_3(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i3.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_4(
              this,
              Invocation.getter(#streamQueries),
            ),
            returnValueForMissingStub: _FakeStreamQueryStore_4(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i4.StreamQueryStore);

  @override
  _i3.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_5(
              this,
              Invocation.getter(#resolvedEngine),
            ),
            returnValueForMissingStub: _FakeDatabaseConnectionUser_5(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i3.DatabaseConnectionUser);

  @override
  _i2.$CachesTableTable get cachesTable =>
      (super.noSuchMethod(
            Invocation.getter(#cachesTable),
            returnValue: _Fake$CachesTableTable_6(
              this,
              Invocation.getter(#cachesTable),
            ),
            returnValueForMissingStub: _Fake$CachesTableTable_6(
              this,
              Invocation.getter(#cachesTable),
            ),
          )
          as _i2.$CachesTableTable);

  @override
  _i5.CacheDaoManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _FakeCacheDaoManager_7(
              this,
              Invocation.getter(#managers),
            ),
            returnValueForMissingStub: _FakeCacheDaoManager_7(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i5.CacheDaoManager);

  @override
  _i6.Stream<String?> watch(String? workspaceId, String? kind, String? key) =>
      (super.noSuchMethod(
            Invocation.method(#watch, [workspaceId, kind, key]),
            returnValue: _i6.Stream<String?>.empty(),
            returnValueForMissingStub: _i6.Stream<String?>.empty(),
          )
          as _i6.Stream<String?>);

  @override
  _i6.Future<String?> read(String? workspaceId, String? kind, String? key) =>
      (super.noSuchMethod(
            Invocation.method(#read, [workspaceId, kind, key]),
            returnValue: _i6.Future<String?>.value(),
            returnValueForMissingStub: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> put(
    String? workspaceId,
    String? kind,
    String? key,
    String? payload,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#put, [workspaceId, kind, key, payload]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteEntry(
    String? workspaceId,
    String? kind,
    String? key,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEntry, [workspaceId, kind, key]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteKind(String? workspaceId, String? kind) =>
      (super.noSuchMethod(
            Invocation.method(#deleteKind, [workspaceId, kind]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteKindWithPrefix(
    String? workspaceId,
    String? kind,
    String? keyPrefix,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteKindWithPrefix, [
              workspaceId,
              kind,
              keyPrefix,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Stream<T> createStream<T extends Object>(
    _i4.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i6.Stream<T>.empty(),
            returnValueForMissingStub: _i6.Stream<T>.empty(),
          )
          as _i6.Stream<T>);

  @override
  T alias<T, D>(_i3.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i14.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
            returnValueForMissingStub: _i14.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i3.TableInfo<_i3.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i3.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Stream<Set<_i3.TableUpdate>> tableUpdates([
    _i3.TableUpdateQuery? query = const _i3.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i6.Stream<Set<_i3.TableUpdate>>.empty(),
            returnValueForMissingStub: _i6.Stream<Set<_i3.TableUpdate>>.empty(),
          )
          as _i6.Stream<Set<_i3.TableUpdate>>);

  @override
  _i6.Future<T> doWhenOpened<T>(
    _i6.FutureOr<T> Function(_i3.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_8<T>(this, Invocation.method(#doWhenOpened, [fn])),
            returnValueForMissingStub:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_8<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i6.Future<T>);

  @override
  _i3.InsertStatement<T, D> into<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_9<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
            returnValueForMissingStub: _FakeInsertStatement_9<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i3.InsertStatement<T, D>);

  @override
  _i3.UpdateStatement<Tbl, R> update<Tbl extends _i3.Table, R>(
    _i3.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_10<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
            returnValueForMissingStub: _FakeUpdateStatement_10<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i3.UpdateStatement<Tbl, R>);

  @override
  _i3.SimpleSelectStatement<T, R> select<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_11<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
            returnValueForMissingStub: _FakeSimpleSelectStatement_11<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i3.SimpleSelectStatement<T, R>);

  @override
  _i3.JoinedSelectStatement<T, R> selectOnly<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_12<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
            returnValueForMissingStub: _FakeJoinedSelectStatement_12<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i3.JoinedSelectStatement<T, R>);

  @override
  _i3.BaseSelectStatement<_i3.TypedResult> selectExpressions(
    Iterable<_i3.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_13<_i3.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
            returnValueForMissingStub:
                _FakeBaseSelectStatement_13<_i3.TypedResult>(
                  this,
                  Invocation.method(#selectExpressions, [columns]),
                ),
          )
          as _i3.BaseSelectStatement<_i3.TypedResult>);

  @override
  _i3.DeleteStatement<T, D> delete<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_14<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
            returnValueForMissingStub: _FakeDeleteStatement_14<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i3.DeleteStatement<T, D>);

  @override
  _i6.Future<int> customUpdate(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i6.Future<int>.value(0),
            returnValueForMissingStub: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> customInsert(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i6.Future<int>.value(0),
            returnValueForMissingStub: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i3.QueryRow>> customWriteReturning(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i6.Future<List<_i3.QueryRow>>.value(<_i3.QueryRow>[]),
            returnValueForMissingStub: _i6.Future<List<_i3.QueryRow>>.value(
              <_i3.QueryRow>[],
            ),
          )
          as _i6.Future<List<_i3.QueryRow>>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelect(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_15<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
            returnValueForMissingStub: _FakeSelectable_15<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelectQuery(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_15<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
            returnValueForMissingStub: _FakeSelectable_15<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i6.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<T> transaction<T>(
    _i6.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_8<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
            returnValueForMissingStub:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_8<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i6.Future<T>);

  @override
  _i6.Future<T> exclusively<T>(_i6.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_8<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
            returnValueForMissingStub:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_8<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i6.Future<T>);

  @override
  _i6.Future<void> batch(_i6.FutureOr<void> Function(_i3.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<T> runWithInterceptor<T>(
    _i6.Future<T> Function()? action, {
    required _i3.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_8<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
            returnValueForMissingStub:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_8<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i6.Future<T>);

  @override
  _i3.GenerationContext $write(
    _i3.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_16(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
            returnValueForMissingStub: _FakeGenerationContext_16(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_16(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
            returnValueForMissingStub: _FakeGenerationContext_16(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [ReviewDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockReviewDao extends _i1.Mock implements _i7.ReviewDao {
  @override
  _i2.AppDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeAppDatabase_0(
              this,
              Invocation.getter(#attachedDatabase),
            ),
            returnValueForMissingStub: _FakeAppDatabase_0(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i2.AppDatabase);

  @override
  _i3.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_1(
              this,
              Invocation.getter(#connection),
            ),
            returnValueForMissingStub: _FakeDatabaseConnection_1(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i3.DatabaseConnection);

  @override
  _i3.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_2(
              this,
              Invocation.getter(#options),
            ),
            returnValueForMissingStub: _FakeDriftDatabaseOptions_2(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i3.DriftDatabaseOptions);

  @override
  _i3.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i14.dummyValue<_i3.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
            returnValueForMissingStub: _i14.dummyValue<_i3.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i3.SqlTypes);

  @override
  _i3.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_3(
              this,
              Invocation.getter(#executor),
            ),
            returnValueForMissingStub: _FakeQueryExecutor_3(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i3.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_4(
              this,
              Invocation.getter(#streamQueries),
            ),
            returnValueForMissingStub: _FakeStreamQueryStore_4(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i4.StreamQueryStore);

  @override
  _i3.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_5(
              this,
              Invocation.getter(#resolvedEngine),
            ),
            returnValueForMissingStub: _FakeDatabaseConnectionUser_5(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i3.DatabaseConnectionUser);

  @override
  _i2.$ReviewDraftsTable get reviewDrafts =>
      (super.noSuchMethod(
            Invocation.getter(#reviewDrafts),
            returnValue: _Fake$ReviewDraftsTable_17(
              this,
              Invocation.getter(#reviewDrafts),
            ),
            returnValueForMissingStub: _Fake$ReviewDraftsTable_17(
              this,
              Invocation.getter(#reviewDrafts),
            ),
          )
          as _i2.$ReviewDraftsTable);

  @override
  _i7.ReviewDaoManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _FakeReviewDaoManager_18(
              this,
              Invocation.getter(#managers),
            ),
            returnValueForMissingStub: _FakeReviewDaoManager_18(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i7.ReviewDaoManager);

  @override
  _i6.Future<void> upsertDraft(
    String? owner,
    String? repo,
    int? prNumber,
    String? commentText,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upsertDraft, [
              owner,
              repo,
              prNumber,
              commentText,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> getDraft(String? owner, String? repo, int? prNumber) =>
      (super.noSuchMethod(
            Invocation.method(#getDraft, [owner, repo, prNumber]),
            returnValue: _i6.Future<String?>.value(),
            returnValueForMissingStub: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> clearDraft(String? owner, String? repo, int? prNumber) =>
      (super.noSuchMethod(
            Invocation.method(#clearDraft, [owner, repo, prNumber]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Stream<T> createStream<T extends Object>(
    _i4.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i6.Stream<T>.empty(),
            returnValueForMissingStub: _i6.Stream<T>.empty(),
          )
          as _i6.Stream<T>);

  @override
  T alias<T, D>(_i3.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i14.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
            returnValueForMissingStub: _i14.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i3.TableInfo<_i3.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i3.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Stream<Set<_i3.TableUpdate>> tableUpdates([
    _i3.TableUpdateQuery? query = const _i3.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i6.Stream<Set<_i3.TableUpdate>>.empty(),
            returnValueForMissingStub: _i6.Stream<Set<_i3.TableUpdate>>.empty(),
          )
          as _i6.Stream<Set<_i3.TableUpdate>>);

  @override
  _i6.Future<T> doWhenOpened<T>(
    _i6.FutureOr<T> Function(_i3.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_8<T>(this, Invocation.method(#doWhenOpened, [fn])),
            returnValueForMissingStub:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_8<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i6.Future<T>);

  @override
  _i3.InsertStatement<T, D> into<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_9<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
            returnValueForMissingStub: _FakeInsertStatement_9<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i3.InsertStatement<T, D>);

  @override
  _i3.UpdateStatement<Tbl, R> update<Tbl extends _i3.Table, R>(
    _i3.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_10<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
            returnValueForMissingStub: _FakeUpdateStatement_10<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i3.UpdateStatement<Tbl, R>);

  @override
  _i3.SimpleSelectStatement<T, R> select<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_11<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
            returnValueForMissingStub: _FakeSimpleSelectStatement_11<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i3.SimpleSelectStatement<T, R>);

  @override
  _i3.JoinedSelectStatement<T, R> selectOnly<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_12<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
            returnValueForMissingStub: _FakeJoinedSelectStatement_12<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i3.JoinedSelectStatement<T, R>);

  @override
  _i3.BaseSelectStatement<_i3.TypedResult> selectExpressions(
    Iterable<_i3.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_13<_i3.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
            returnValueForMissingStub:
                _FakeBaseSelectStatement_13<_i3.TypedResult>(
                  this,
                  Invocation.method(#selectExpressions, [columns]),
                ),
          )
          as _i3.BaseSelectStatement<_i3.TypedResult>);

  @override
  _i3.DeleteStatement<T, D> delete<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_14<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
            returnValueForMissingStub: _FakeDeleteStatement_14<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i3.DeleteStatement<T, D>);

  @override
  _i6.Future<int> customUpdate(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i6.Future<int>.value(0),
            returnValueForMissingStub: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> customInsert(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i6.Future<int>.value(0),
            returnValueForMissingStub: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i3.QueryRow>> customWriteReturning(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i6.Future<List<_i3.QueryRow>>.value(<_i3.QueryRow>[]),
            returnValueForMissingStub: _i6.Future<List<_i3.QueryRow>>.value(
              <_i3.QueryRow>[],
            ),
          )
          as _i6.Future<List<_i3.QueryRow>>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelect(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_15<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
            returnValueForMissingStub: _FakeSelectable_15<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelectQuery(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_15<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
            returnValueForMissingStub: _FakeSelectable_15<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i6.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<T> transaction<T>(
    _i6.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_8<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
            returnValueForMissingStub:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_8<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i6.Future<T>);

  @override
  _i6.Future<T> exclusively<T>(_i6.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_8<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
            returnValueForMissingStub:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_8<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i6.Future<T>);

  @override
  _i6.Future<void> batch(_i6.FutureOr<void> Function(_i3.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<T> runWithInterceptor<T>(
    _i6.Future<T> Function()? action, {
    required _i3.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_8<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
            returnValueForMissingStub:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_8<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i6.Future<T>);

  @override
  _i3.GenerationContext $write(
    _i3.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_16(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
            returnValueForMissingStub: _FakeGenerationContext_16(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_16(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
            returnValueForMissingStub: _FakeGenerationContext_16(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [GitHubApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGitHubApiClient extends _i1.Mock implements _i15.GitHubApiClient {
  @override
  _i8.GitHubPrClient get pr =>
      (super.noSuchMethod(
            Invocation.getter(#pr),
            returnValue: _FakeGitHubPrClient_19(this, Invocation.getter(#pr)),
            returnValueForMissingStub: _FakeGitHubPrClient_19(
              this,
              Invocation.getter(#pr),
            ),
          )
          as _i8.GitHubPrClient);

  @override
  _i9.GitHubGraphQLClient get graphql =>
      (super.noSuchMethod(
            Invocation.getter(#graphql),
            returnValue: _FakeGitHubGraphQLClient_20(
              this,
              Invocation.getter(#graphql),
            ),
            returnValueForMissingStub: _FakeGitHubGraphQLClient_20(
              this,
              Invocation.getter(#graphql),
            ),
          )
          as _i9.GitHubGraphQLClient);

  @override
  _i10.GitHubContentClient get content =>
      (super.noSuchMethod(
            Invocation.getter(#content),
            returnValue: _FakeGitHubContentClient_21(
              this,
              Invocation.getter(#content),
            ),
            returnValueForMissingStub: _FakeGitHubContentClient_21(
              this,
              Invocation.getter(#content),
            ),
          )
          as _i10.GitHubContentClient);
}

/// A class which mocks [GitHubPrClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGitHubPrClient extends _i1.Mock implements _i8.GitHubPrClient {
  @override
  _i6.Future<_i8.PaginatedPullRequests> listOpenPullRequestsPage(
    String? owner,
    String? repo, {
    int? page = 1,
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listOpenPullRequestsPage,
              [owner, repo],
              {#page: page, #cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<_i8.PaginatedPullRequests>.value(
              _FakePaginatedPullRequests_22(
                this,
                Invocation.method(
                  #listOpenPullRequestsPage,
                  [owner, repo],
                  {#page: page, #cancelToken: cancelToken},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i8.PaginatedPullRequests>.value(
                  _FakePaginatedPullRequests_22(
                    this,
                    Invocation.method(
                      #listOpenPullRequestsPage,
                      [owner, repo],
                      {#page: page, #cancelToken: cancelToken},
                    ),
                  ),
                ),
          )
          as _i6.Future<_i8.PaginatedPullRequests>);

  @override
  _i6.Future<List<_i17.GitHubPullRequest>> listRequestedReviews(
    String? owner,
    String? repo, {
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listRequestedReviews,
              [owner, repo],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<List<_i17.GitHubPullRequest>>.value(
              <_i17.GitHubPullRequest>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i17.GitHubPullRequest>>.value(
                  <_i17.GitHubPullRequest>[],
                ),
          )
          as _i6.Future<List<_i17.GitHubPullRequest>>);

  @override
  _i6.Future<Set<int>> listReviewedByMePrNumbers(
    String? owner,
    String? repo, {
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listReviewedByMePrNumbers,
              [owner, repo],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<Set<int>>.value(<int>{}),
            returnValueForMissingStub: _i6.Future<Set<int>>.value(<int>{}),
          )
          as _i6.Future<Set<int>>);

  @override
  _i6.Future<_i17.GitHubPullRequest?> getPullRequest(
    String? owner,
    String? repo,
    int? number, {
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPullRequest,
              [owner, repo, number],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<_i17.GitHubPullRequest?>.value(),
            returnValueForMissingStub:
                _i6.Future<_i17.GitHubPullRequest?>.value(),
          )
          as _i6.Future<_i17.GitHubPullRequest?>);

  @override
  _i6.Future<_i13.GitHubReactionSummary?> getIssueReactionSummary(
    String? owner,
    String? repo,
    int? issueNumber, {
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getIssueReactionSummary,
              [owner, repo, issueNumber],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<_i13.GitHubReactionSummary?>.value(),
            returnValueForMissingStub:
                _i6.Future<_i13.GitHubReactionSummary?>.value(),
          )
          as _i6.Future<_i13.GitHubReactionSummary?>);

  @override
  _i6.Future<String> getPullRequestDiff(
    String? owner,
    String? repo,
    int? number, {
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPullRequestDiff,
              [owner, repo, number],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(
                  #getPullRequestDiff,
                  [owner, repo, number],
                  {#cancelToken: cancelToken},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(
                  #getPullRequestDiff,
                  [owner, repo, number],
                  {#cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<_i18.GitHubPullRequestFile>> listPullRequestFiles(
    String? owner,
    String? repo,
    int? number, {
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listPullRequestFiles,
              [owner, repo, number],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<List<_i18.GitHubPullRequestFile>>.value(
              <_i18.GitHubPullRequestFile>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i18.GitHubPullRequestFile>>.value(
                  <_i18.GitHubPullRequestFile>[],
                ),
          )
          as _i6.Future<List<_i18.GitHubPullRequestFile>>);

  @override
  _i6.Stream<List<_i18.GitHubPullRequestFile>> streamPullRequestFiles(
    String? owner,
    String? repo,
    int? number, {
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #streamPullRequestFiles,
              [owner, repo, number],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i6.Stream<List<_i18.GitHubPullRequestFile>>.empty(),
            returnValueForMissingStub:
                _i6.Stream<List<_i18.GitHubPullRequestFile>>.empty(),
          )
          as _i6.Stream<List<_i18.GitHubPullRequestFile>>);

  @override
  _i6.Future<List<_i19.GitHubCommit>> listPullRequestCommits(
    String? owner,
    String? repo,
    int? number, {
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listPullRequestCommits,
              [owner, repo, number],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<List<_i19.GitHubCommit>>.value(
              <_i19.GitHubCommit>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i19.GitHubCommit>>.value(
                  <_i19.GitHubCommit>[],
                ),
          )
          as _i6.Future<List<_i19.GitHubCommit>>);

  @override
  _i6.Future<List<_i19.GitHubCommit>> listAllPullRequestCommits(
    String? owner,
    String? repo,
    int? number, {
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listAllPullRequestCommits,
              [owner, repo, number],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<List<_i19.GitHubCommit>>.value(
              <_i19.GitHubCommit>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i19.GitHubCommit>>.value(
                  <_i19.GitHubCommit>[],
                ),
          )
          as _i6.Future<List<_i19.GitHubCommit>>);

  @override
  _i6.Future<_i19.GitHubCommit?> getCommit(
    String? owner,
    String? repo,
    String? sha, {
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCommit,
              [owner, repo, sha],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<_i19.GitHubCommit?>.value(),
            returnValueForMissingStub: _i6.Future<_i19.GitHubCommit?>.value(),
          )
          as _i6.Future<_i19.GitHubCommit?>);

  @override
  _i6.Future<List<_i18.GitHubPullRequestFile>> getCommitFiles(
    String? owner,
    String? repo,
    String? sha, {
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCommitFiles,
              [owner, repo, sha],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<List<_i18.GitHubPullRequestFile>>.value(
              <_i18.GitHubPullRequestFile>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i18.GitHubPullRequestFile>>.value(
                  <_i18.GitHubPullRequestFile>[],
                ),
          )
          as _i6.Future<List<_i18.GitHubPullRequestFile>>);

  @override
  _i6.Future<List<_i12.GitHubReview>> listPullRequestReviews(
    String? owner,
    String? repo,
    int? number, {
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listPullRequestReviews,
              [owner, repo, number],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<List<_i12.GitHubReview>>.value(
              <_i12.GitHubReview>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i12.GitHubReview>>.value(
                  <_i12.GitHubReview>[],
                ),
          )
          as _i6.Future<List<_i12.GitHubReview>>);

  @override
  _i6.Future<List<_i11.GitHubReviewComment>> listPullRequestReviewComments(
    String? owner,
    String? repo,
    int? number, {
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listPullRequestReviewComments,
              [owner, repo, number],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<List<_i11.GitHubReviewComment>>.value(
              <_i11.GitHubReviewComment>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i11.GitHubReviewComment>>.value(
                  <_i11.GitHubReviewComment>[],
                ),
          )
          as _i6.Future<List<_i11.GitHubReviewComment>>);

  @override
  _i6.Future<List<_i20.GitHubIssueComment>> listIssueComments(
    String? owner,
    String? repo,
    int? number, {
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listIssueComments,
              [owner, repo, number],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<List<_i20.GitHubIssueComment>>.value(
              <_i20.GitHubIssueComment>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i20.GitHubIssueComment>>.value(
                  <_i20.GitHubIssueComment>[],
                ),
          )
          as _i6.Future<List<_i20.GitHubIssueComment>>);

  @override
  _i6.Future<List<_i21.GitHubCheckRun>> listCheckRuns(
    String? owner,
    String? repo,
    String? ref, {
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listCheckRuns,
              [owner, repo, ref],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<List<_i21.GitHubCheckRun>>.value(
              <_i21.GitHubCheckRun>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i21.GitHubCheckRun>>.value(
                  <_i21.GitHubCheckRun>[],
                ),
          )
          as _i6.Future<List<_i21.GitHubCheckRun>>);

  @override
  _i6.Future<List<_i22.GitHubWorkflowRun>> listWorkflowRuns(
    String? owner,
    String? repo,
    String? headSha, {
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listWorkflowRuns,
              [owner, repo, headSha],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<List<_i22.GitHubWorkflowRun>>.value(
              <_i22.GitHubWorkflowRun>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i22.GitHubWorkflowRun>>.value(
                  <_i22.GitHubWorkflowRun>[],
                ),
          )
          as _i6.Future<List<_i22.GitHubWorkflowRun>>);

  @override
  _i6.Future<_i11.GitHubReviewComment> postReviewComment(
    String? owner,
    String? repo, {
    required int? prNumber,
    required String? commitSha,
    required String? path,
    required int? line,
    required String? side,
    required String? body,
    int? startLine,
    String? startSide,
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postReviewComment,
              [owner, repo],
              {
                #prNumber: prNumber,
                #commitSha: commitSha,
                #path: path,
                #line: line,
                #side: side,
                #body: body,
                #startLine: startLine,
                #startSide: startSide,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i6.Future<_i11.GitHubReviewComment>.value(
              _FakeGitHubReviewComment_23(
                this,
                Invocation.method(
                  #postReviewComment,
                  [owner, repo],
                  {
                    #prNumber: prNumber,
                    #commitSha: commitSha,
                    #path: path,
                    #line: line,
                    #side: side,
                    #body: body,
                    #startLine: startLine,
                    #startSide: startSide,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i11.GitHubReviewComment>.value(
                  _FakeGitHubReviewComment_23(
                    this,
                    Invocation.method(
                      #postReviewComment,
                      [owner, repo],
                      {
                        #prNumber: prNumber,
                        #commitSha: commitSha,
                        #path: path,
                        #line: line,
                        #side: side,
                        #body: body,
                        #startLine: startLine,
                        #startSide: startSide,
                        #cancelToken: cancelToken,
                      },
                    ),
                  ),
                ),
          )
          as _i6.Future<_i11.GitHubReviewComment>);

  @override
  _i6.Future<_i11.GitHubReviewComment> replyToReviewComment(
    String? owner,
    String? repo, {
    required int? prNumber,
    required int? parentCommentId,
    required String? body,
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #replyToReviewComment,
              [owner, repo],
              {
                #prNumber: prNumber,
                #parentCommentId: parentCommentId,
                #body: body,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i6.Future<_i11.GitHubReviewComment>.value(
              _FakeGitHubReviewComment_23(
                this,
                Invocation.method(
                  #replyToReviewComment,
                  [owner, repo],
                  {
                    #prNumber: prNumber,
                    #parentCommentId: parentCommentId,
                    #body: body,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i11.GitHubReviewComment>.value(
                  _FakeGitHubReviewComment_23(
                    this,
                    Invocation.method(
                      #replyToReviewComment,
                      [owner, repo],
                      {
                        #prNumber: prNumber,
                        #parentCommentId: parentCommentId,
                        #body: body,
                        #cancelToken: cancelToken,
                      },
                    ),
                  ),
                ),
          )
          as _i6.Future<_i11.GitHubReviewComment>);

  @override
  _i6.Future<void> deleteReviewComment(
    String? owner,
    String? repo, {
    required int? commentId,
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteReviewComment,
              [owner, repo],
              {#commentId: commentId, #cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i11.GitHubReviewComment> editReviewComment(
    String? owner,
    String? repo, {
    required int? commentId,
    required String? body,
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #editReviewComment,
              [owner, repo],
              {#commentId: commentId, #body: body, #cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<_i11.GitHubReviewComment>.value(
              _FakeGitHubReviewComment_23(
                this,
                Invocation.method(
                  #editReviewComment,
                  [owner, repo],
                  {
                    #commentId: commentId,
                    #body: body,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i11.GitHubReviewComment>.value(
                  _FakeGitHubReviewComment_23(
                    this,
                    Invocation.method(
                      #editReviewComment,
                      [owner, repo],
                      {
                        #commentId: commentId,
                        #body: body,
                        #cancelToken: cancelToken,
                      },
                    ),
                  ),
                ),
          )
          as _i6.Future<_i11.GitHubReviewComment>);

  @override
  _i6.Future<_i12.GitHubReview> submitReview(
    String? owner,
    String? repo, {
    required int? prNumber,
    required String? event,
    String? body,
    String? commitId,
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #submitReview,
              [owner, repo],
              {
                #prNumber: prNumber,
                #event: event,
                #body: body,
                #commitId: commitId,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i6.Future<_i12.GitHubReview>.value(
              _FakeGitHubReview_24(
                this,
                Invocation.method(
                  #submitReview,
                  [owner, repo],
                  {
                    #prNumber: prNumber,
                    #event: event,
                    #body: body,
                    #commitId: commitId,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i12.GitHubReview>.value(
              _FakeGitHubReview_24(
                this,
                Invocation.method(
                  #submitReview,
                  [owner, repo],
                  {
                    #prNumber: prNumber,
                    #event: event,
                    #body: body,
                    #commitId: commitId,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i12.GitHubReview>);

  @override
  _i6.Future<Map<String, dynamic>> createPullRequest(
    String? owner,
    String? repo, {
    required String? title,
    required String? body,
    required String? head,
    required String? base,
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createPullRequest,
              [owner, repo],
              {
                #title: title,
                #body: body,
                #head: head,
                #base: base,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i13.GitHubReaction> createReviewCommentReaction(
    String? owner,
    String? repo, {
    required int? commentId,
    required String? content,
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createReviewCommentReaction,
              [owner, repo],
              {
                #commentId: commentId,
                #content: content,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i6.Future<_i13.GitHubReaction>.value(
              _FakeGitHubReaction_25(
                this,
                Invocation.method(
                  #createReviewCommentReaction,
                  [owner, repo],
                  {
                    #commentId: commentId,
                    #content: content,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i13.GitHubReaction>.value(
              _FakeGitHubReaction_25(
                this,
                Invocation.method(
                  #createReviewCommentReaction,
                  [owner, repo],
                  {
                    #commentId: commentId,
                    #content: content,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i13.GitHubReaction>);

  @override
  _i6.Future<void> deleteReviewCommentReaction(
    String? owner,
    String? repo, {
    required int? commentId,
    required int? reactionId,
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteReviewCommentReaction,
              [owner, repo],
              {
                #commentId: commentId,
                #reactionId: reactionId,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i13.GitHubReaction>> listReviewCommentReactions(
    String? owner,
    String? repo, {
    required int? commentId,
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listReviewCommentReactions,
              [owner, repo],
              {#commentId: commentId, #cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<List<_i13.GitHubReaction>>.value(
              <_i13.GitHubReaction>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i13.GitHubReaction>>.value(
                  <_i13.GitHubReaction>[],
                ),
          )
          as _i6.Future<List<_i13.GitHubReaction>>);

  @override
  _i6.Future<_i13.GitHubReaction> createIssueCommentReaction(
    String? owner,
    String? repo, {
    required int? commentId,
    required String? content,
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createIssueCommentReaction,
              [owner, repo],
              {
                #commentId: commentId,
                #content: content,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i6.Future<_i13.GitHubReaction>.value(
              _FakeGitHubReaction_25(
                this,
                Invocation.method(
                  #createIssueCommentReaction,
                  [owner, repo],
                  {
                    #commentId: commentId,
                    #content: content,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i13.GitHubReaction>.value(
              _FakeGitHubReaction_25(
                this,
                Invocation.method(
                  #createIssueCommentReaction,
                  [owner, repo],
                  {
                    #commentId: commentId,
                    #content: content,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i13.GitHubReaction>);

  @override
  _i6.Future<void> deleteIssueCommentReaction(
    String? owner,
    String? repo, {
    required int? commentId,
    required int? reactionId,
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteIssueCommentReaction,
              [owner, repo],
              {
                #commentId: commentId,
                #reactionId: reactionId,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i13.GitHubReaction>> listIssueCommentReactions(
    String? owner,
    String? repo, {
    required int? commentId,
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listIssueCommentReactions,
              [owner, repo],
              {#commentId: commentId, #cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<List<_i13.GitHubReaction>>.value(
              <_i13.GitHubReaction>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i13.GitHubReaction>>.value(
                  <_i13.GitHubReaction>[],
                ),
          )
          as _i6.Future<List<_i13.GitHubReaction>>);

  @override
  _i6.Future<_i13.GitHubReaction> createIssueReaction(
    String? owner,
    String? repo, {
    required int? issueNumber,
    required String? content,
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createIssueReaction,
              [owner, repo],
              {
                #issueNumber: issueNumber,
                #content: content,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i6.Future<_i13.GitHubReaction>.value(
              _FakeGitHubReaction_25(
                this,
                Invocation.method(
                  #createIssueReaction,
                  [owner, repo],
                  {
                    #issueNumber: issueNumber,
                    #content: content,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i13.GitHubReaction>.value(
              _FakeGitHubReaction_25(
                this,
                Invocation.method(
                  #createIssueReaction,
                  [owner, repo],
                  {
                    #issueNumber: issueNumber,
                    #content: content,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i13.GitHubReaction>);

  @override
  _i6.Future<void> deleteIssueReaction(
    String? owner,
    String? repo, {
    required int? issueNumber,
    required int? reactionId,
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteIssueReaction,
              [owner, repo],
              {
                #issueNumber: issueNumber,
                #reactionId: reactionId,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i13.GitHubReaction>> listIssueReactions(
    String? owner,
    String? repo, {
    required int? issueNumber,
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listIssueReactions,
              [owner, repo],
              {#issueNumber: issueNumber, #cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<List<_i13.GitHubReaction>>.value(
              <_i13.GitHubReaction>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i13.GitHubReaction>>.value(
                  <_i13.GitHubReaction>[],
                ),
          )
          as _i6.Future<List<_i13.GitHubReaction>>);

  @override
  _i6.Future<Map<String, dynamic>> mergePullRequest(
    String? owner,
    String? repo, {
    required int? prNumber,
    required String? mergeMethod,
    String? commitTitle,
    String? commitMessage,
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #mergePullRequest,
              [owner, repo],
              {
                #prNumber: prNumber,
                #mergeMethod: mergeMethod,
                #commitTitle: commitTitle,
                #commitMessage: commitMessage,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> closePullRequest(
    String? owner,
    String? repo, {
    required int? prNumber,
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #closePullRequest,
              [owner, repo],
              {#prNumber: prNumber, #cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [GitHubContentClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGitHubContentClient extends _i1.Mock
    implements _i10.GitHubContentClient {
  @override
  _i6.Future<String> getFileContent(
    String? owner,
    String? repo,
    String? path,
    String? ref, {
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getFileContent,
              [owner, repo, path, ref],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(
                  #getFileContent,
                  [owner, repo, path, ref],
                  {#cancelToken: cancelToken},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(
                  #getFileContent,
                  [owner, repo, path, ref],
                  {#cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> createBlob(
    String? owner,
    String? repo,
    String? base64Content, {
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createBlob,
              [owner, repo, base64Content],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(
                  #createBlob,
                  [owner, repo, base64Content],
                  {#cancelToken: cancelToken},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(
                  #createBlob,
                  [owner, repo, base64Content],
                  {#cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> createFileContent(
    String? owner,
    String? repo,
    String? path,
    String? base64Content,
    String? message, {
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createFileContent,
              [owner, repo, path, base64Content, message],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(
                  #createFileContent,
                  [owner, repo, path, base64Content, message],
                  {#cancelToken: cancelToken},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(
                  #createFileContent,
                  [owner, repo, path, base64Content, message],
                  {#cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<_i23.GitHubUser?> getAuthenticatedUser({
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAuthenticatedUser, [], {
              #cancelToken: cancelToken,
            }),
            returnValue: _i6.Future<_i23.GitHubUser?>.value(),
            returnValueForMissingStub: _i6.Future<_i23.GitHubUser?>.value(),
          )
          as _i6.Future<_i23.GitHubUser?>);

  @override
  _i6.Future<_i23.GitHubUser?> getUserByLogin(
    String? login, {
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUserByLogin,
              [login],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<_i23.GitHubUser?>.value(),
            returnValueForMissingStub: _i6.Future<_i23.GitHubUser?>.value(),
          )
          as _i6.Future<_i23.GitHubUser?>);

  @override
  _i6.Future<String> getCollaboratorPermission(
    String? owner,
    String? repo,
    String? username, {
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCollaboratorPermission,
              [owner, repo, username],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(
                  #getCollaboratorPermission,
                  [owner, repo, username],
                  {#cancelToken: cancelToken},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(
                  #getCollaboratorPermission,
                  [owner, repo, username],
                  {#cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<_i23.GitHubUser>> getOrganizationMembers(
    String? org, {
    _i16.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getOrganizationMembers,
              [org],
              {#cancelToken: cancelToken},
            ),
            returnValue: _i6.Future<List<_i23.GitHubUser>>.value(
              <_i23.GitHubUser>[],
            ),
            returnValueForMissingStub: _i6.Future<List<_i23.GitHubUser>>.value(
              <_i23.GitHubUser>[],
            ),
          )
          as _i6.Future<List<_i23.GitHubUser>>);
}
