// GENERATED BY tool/gen_icon_seams.py — DO NOT EDIT.
// The icon constants below are self-documenting (name == glyph); per-field doc
// comments would be pure noise.
// ignore_for_file: public_member_api_docs
import 'package:flutter/widgets.dart';

/// The Phosphor glyphs cc_ui's own components (and the gallery / cc_ui
/// tests) need.
///
/// cc_ui owns the Phosphor Regular font itself (`fonts/Phosphor-Regular.ttf`)
/// and deliberately depends on no icon package. Such a package exposes each
/// style as a class of ~1530 `static const IconData` fields; on Flutter web
/// the dev compiler (DDC) links a library the first time any member is
/// touched and linking that giant class overflows the JS stack — crashing
/// `flutter run -d chrome` before the first frame. Since cc_ui is the shared
/// design system, that would break the web build for every consumer.
/// Declaring only the codepoints used avoids the link and lets the icon
/// tree-shaker subset the font down to what is actually rendered.
///
/// Generated by `tool/gen_icon_seams.py` — edit the mapping there, never
/// this file. cc_ui is purist — built on `package:flutter/widgets.dart`
/// only — and this keeps it web-safe too.
@staticIconProvider
abstract final class CcIcons {
  static const String _family = 'PhosphorRegular';
  static const String _package = 'cc_ui';

  static const IconData activity = IconData(
    0xe000,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData bell = IconData(
    0xe0ce,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData bookmark = IconData(
    0xe0ea,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData bot = IconData(
    0xe762,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData boxes = IconData(
    0xe390,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData calendarClock = IconData(
    0xe108,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData calendarX = IconData(
    0xe10c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData check = IconData(
    0xe182,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData chevronDown = IconData(
    0xe136,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData chevronRight = IconData(
    0xe13a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData circleCheck = IconData(
    0xe184,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData circleDashed = IconData(
    0xe602,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData circleX = IconData(
    0xe4f8,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData clock = IconData(
    0xe19a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData code = IconData(
    0xe1bc,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData copy = IconData(
    0xe1ca,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData cornerLeftUp = IconData(
    0xe04c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData eye = IconData(
    0xe220,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData eyeOff = IconData(
    0xe224,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData feather = IconData(
    0xe9c0,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData fileCode = IconData(
    0xe914,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData fileDiff = IconData(
    0xe27c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData flaskConical = IconData(
    0xe79e,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData folder = IconData(
    0xe24a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData folderGit = IconData(
    0xe24a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData folderGit2 = IconData(
    0xe24a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData folderOpen = IconData(
    0xe256,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData folderTree = IconData(
    0xe260,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gitBranch = IconData(
    0xe278,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gitMerge = IconData(
    0xe280,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gitPullRequest = IconData(
    0xe282,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gitPullRequestArrow = IconData(
    0xe282,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gitPullRequestClosed = IconData(
    0xe4f8,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gitPullRequestCreateArrow = IconData(
    0xe282,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData gitPullRequestDraft = IconData(
    0xe602,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData house = IconData(
    0xe2c2,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData inbox = IconData(
    0xe4aa,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData info = IconData(
    0xe2ce,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData keyRound = IconData(
    0xe2d6,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData layers = IconData(
    0xe466,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData layoutDashboard = IconData(
    0xe464,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData listFilter = IconData(
    0xe266,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData listTodo = IconData(
    0xeadc,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData lock = IconData(
    0xe2fa,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData messageSquare = IconData(
    0xe15c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData minus = IconData(
    0xe32a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData palette = IconData(
    0xe6c8,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData pencil = IconData(
    0xe3b4,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData pencilRuler = IconData(
    0xe906,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData play = IconData(
    0xe3d0,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData plus = IconData(
    0xe3d4,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData refreshCw = IconData(
    0xe036,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData rocket = IconData(
    0xe3fc,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData search = IconData(
    0xe30c,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData settings = IconData(
    0xe270,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData sparkles = IconData(
    0xe6a2,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData star = IconData(
    0xe46a,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData tag = IconData(
    0xe478,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData trash2 = IconData(
    0xe4a6,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData triangleAlert = IconData(
    0xe4e0,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData user = IconData(
    0xe4c2,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData users = IconData(
    0xe4d6,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData workflow = IconData(
    0xe6ec,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData x = IconData(
    0xe4f6,
    fontFamily: _family,
    fontPackage: _package,
  );
  static const IconData zap = IconData(
    0xe2de,
    fontFamily: _family,
    fontPackage: _package,
  );
}
